export const normalizeText=(value:string):string=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
export function normalizePhone(value:string|null|undefined):string|null{if(!value)return null;let d=value.replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('54'))d=d.slice(2);if(d.startsWith('0'))d=d.slice(1);if(d.length===11&&d.startsWith('9'))d=d.slice(1);if((d.length===11||d.length===12)&&d[2]==='1'&&d[3]==='5')d=d.slice(0,2)+d.slice(4);if(d.length===12&&d.startsWith('911'))d=d.slice(1);return d.length>=10&&d.length<=11?`54${d}`:null}
const trigrams=(s:string)=>{const padded=`  ${normalizeText(s)} `,out:string[]=[];for(let i=0;i<padded.length-2;i++)out.push(padded.slice(i,i+3));return out};
export function trigramSimilarity(a:string,b:string):number{const aa=trigrams(a),bb=trigrams(b);if(!aa.length&&!bb.length)return 1;const counts=new Map<string,number>();for(const x of aa)counts.set(x,(counts.get(x)??0)+1);let common=0;for(const x of bb){const n=counts.get(x)??0;if(n){common++;counts.set(x,n-1)}}return (2*common)/(aa.length+bb.length)}
export function wordOverlap(a:string,b:string):number{const aa=new Set(normalizeText(a).split(' ').filter(Boolean)),bb=new Set(normalizeText(b).split(' ').filter(Boolean));if(!aa.size&&!bb.size)return 1;let common=0;for(const x of aa)if(bb.has(x))common++;return common/new Set([...aa,...bb]).size}
export const extractNumbersModels=(s:string):string[]=>normalizeText(s).split(' ').filter(x=>/\d/.test(x));
const sameMultiset=(a:string[],b:string[]):boolean=>{if(a.length!==b.length)return false;const counts=new Map<string,number>();for(const token of a)counts.set(token,(counts.get(token)??0)+1);for(const token of b)counts.set(token,(counts.get(token)??0)-1);return [...counts.values()].every(count=>count===0)};
export function productSimilarity(a:string,b:string):number{const tokensA=normalizeText(a).split(' ').filter(Boolean),tokensB=normalizeText(b).split(' ').filter(Boolean),ma=extractNumbersModels(a),modelsB=extractNumbersModels(b);if(sameMultiset(tokensA,tokensB)&&sameMultiset(ma,modelsB))return 100;const mb=new Set(modelsB),model=ma.length?ma.filter(x=>mb.has(x)).length/Math.max(ma.length,mb.size):mb.size?0:1;return Math.max(0,Math.min(100,Math.round((trigramSimilarity(a,b)*50+wordOverlap(a,b)*30+model*20))))}

