import{z}from'zod';
const optionalEmpty=z.preprocess(v=>v===''?undefined:v,z.string().optional());
export const envSchema=z.object({NODE_ENV:z.enum(['development','test','production']).default('development'),DATABASE_URL:z.string().min(1),PORT:z.coerce.number().int().min(1).max(65535).default(3001),APP_ORIGIN:z.string().url().default('http://localhost:3000'),SESSION_TTL_DAYS:z.coerce.number().int().positive().default(7),SESSION_RENEWAL_PERCENT:z.coerce.number().int().min(1).max(99).default(25),LOGIN_MAX_ATTEMPTS:z.coerce.number().int().positive().default(5),LOGIN_WINDOW_MINUTES:z.coerce.number().int().positive().default(15),THROTTLE_TTL_MS:z.coerce.number().int().positive().default(60000),THROTTLE_LIMIT:z.coerce.number().int().positive().default(100),ADMIN_USERNAME:z.string().min(1).default('admin'),ADMIN_PASSWORD:z.string().min(12),SETTINGS_ENC_KEY:z.string().refine(v=>{try{return keyBytes(v).length===32}catch{return false}},'Debe contener exactamente 32 bytes en base64 o hex'),OPENAI_API_KEY:optionalEmpty,PDF_STORAGE_DRIVER:z.enum(['local','s3']).default('local'),PDF_LOCAL_DIR:z.string().default('storage/pdfs'),S3_ENDPOINT:optionalEmpty,S3_BUCKET:optionalEmpty,S3_ACCESS_KEY:optionalEmpty,S3_SECRET_KEY:optionalEmpty});
export type AppEnv=z.infer<typeof envSchema>;export const loadEnv=(source:NodeJS.ProcessEnv=process.env):AppEnv=>envSchema.parse(source);
export const locale='es-AR',timeZone='America/Argentina/Buenos_Aires',currency='ARS';
import{createCipheriv,createDecipheriv,randomBytes}from'node:crypto';
function keyBytes(value:string):Buffer{if(/^[0-9a-fA-F]{64}$/.test(value))return Buffer.from(value,'hex');if(Buffer.byteLength(value,'utf8')===32)return Buffer.from(value,'utf8');const b=Buffer.from(value,'base64');if(b.length!==32)throw new Error('SETTINGS_ENC_KEY debe contener 32 bytes');return b}
const resolveKey=(key?:string)=>keyBytes(key??process.env.SETTINGS_ENC_KEY??'');
export function encryptSecret(plain:string,key?:string):string{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',resolveKey(key),iv),encrypted=Buffer.concat([cipher.update(plain,'utf8'),cipher.final()]);return[iv,cipher.getAuthTag(),encrypted].map(x=>x.toString('base64')).join(':')}
export function decryptSecret(value:string,key?:string):string{const parts=value.split(':');if(parts.length!==3)throw new Error('Secreto cifrado inválido');const[iv,tag,data]=parts.map(x=>Buffer.from(x!,'base64')),decipher=createDecipheriv('aes-256-gcm',resolveKey(key),iv!);decipher.setAuthTag(tag!);return Buffer.concat([decipher.update(data!),decipher.final()]).toString('utf8')}
export function maskSecret(value:string):string{if(!value)return'';const suffix=value.slice(-4);return value.startsWith('sk-')?`sk-••••${suffix}`:`••••${suffix}`}
