<?php
defined('ABSPATH') || exit;
function tgs_sq_managed($id=0){$id=$id?:get_the_ID();return $id&&get_post_meta($id,'_tgs_managed',true)==='1';}
add_filter('template_include',function($template){return is_singular('product')&&tgs_sq_managed()?TGS_SQ_DIR.'templates/single-landing.php':$template;},99);
add_filter('script_loader_tag',function($tag,$handle){return $handle==='tgs-model-viewer'?str_replace('<script ','<script type="module" ',$tag):$tag;},10,2);add_action('wp_enqueue_scripts',function(){if(!is_singular('product')||!tgs_sq_managed())return;wp_enqueue_style('tgs-landing',TGS_SQ_URL.'assets/tgs-landing.css',[],TGS_SQ_VERSION);wp_enqueue_script('tgs-landing',TGS_SQ_URL.'assets/tgs-landing.js',[],TGS_SQ_VERSION,true);wp_enqueue_script('tgs-model-viewer',TGS_SQ_URL.'assets/model-viewer.min.js',[],TGS_SQ_VERSION,true);});
function tgs_sq_image_html($html,$post_id=0){$id=$post_id?:get_the_ID();if(!tgs_sq_managed($id))return $html;$url=get_post_meta($id,'_tgs_thumbnail_url',true);return $url?'<img class="tgs-product-thumbnail" src="'.esc_url($url).'" alt="'.esc_attr(get_the_title($id)).'" loading="lazy">':$html;}
add_filter('post_thumbnail_html','tgs_sq_image_html',20,2);add_filter('woocommerce_single_product_image_thumbnail_html',fn($html)=>tgs_sq_image_html($html),20);add_filter('woocommerce_product_get_image',function($html,$product){return tgs_sq_image_html($html,$product->get_id());},20,2);
function tgs_sq_default_layout(){return['version'=>1,'tokens'=>['accent'=>'#E31B23','bg'=>'#080B12','text'=>'#F8FAFC','radius'=>24,'font'=>'Inter, system-ui, sans-serif'],'blocks'=>array_map(fn($type)=>['type'=>$type,'visible'=>true],['hero3d','priceBox','addToCartSticky','gallery','specs','description','power','games','compatibility'])];}
function tgs_sq_layout($id){$layout=json_decode((string)get_post_meta($id,'_tgs_layout',true),true);return is_array($layout)&&isset($layout['blocks'])&&is_array($layout['blocks'])?$layout:tgs_sq_default_layout();}
function tgs_sq_render_block($type,$data){$renderer='tgs_sq_block_'.$type;if(function_exists($renderer))$renderer($data);}
function tgs_sq_block_gallery($d){if(!$d['gallery'])return;echo'<section><h2>Galería</h2><div class="tgs-gallery">';foreach($d['gallery'] as $url)echo'<img src="'.esc_url($url).'" alt="Imagen del equipo">';echo'</div></section>';}
function tgs_sq_block_specs($d){echo'<section><h2>Componentes y especificaciones</h2>';foreach($d['items'] as $item){echo'<div class="tgs-item">';if(!empty($item['imageUrl']))echo'<img src="'.esc_url($item['imageUrl']).'" alt="">';echo'<span>'.esc_html($item['name']??'').'</span></div>';}echo'</section>';}
function tgs_sq_block_description($d){$meta=$d['meta'];echo'<section><h2>Descripción</h2>'.wp_kses_post($meta('_tgs_description_html')).'</section>';}
function tgs_sq_block_power($d){echo'<section><h2>Potencia</h2><p>'.esc_html(($d['power']['watts']??'—').' W · fuente '.($d['power']['psu']??'—').' W').'<br><small>'.esc_html($d['power']['note']??'').'</small></p></section>';}
function tgs_sq_block_games($d){echo'<section><h2>Juegos</h2>';foreach($d['games'] as $game)echo'<p><strong>'.esc_html($game['name']??'').'</strong> · '.esc_html($game['tier']??'').'</p>';echo'</section>';}
function tgs_sq_block_compatibility($d){echo'<section><h2>Compatibilidad</h2><ul>';foreach($d['compat'] as $line)echo'<li>'.esc_html($line).'</li>';echo'</ul></section>';}
function tgs_sq_block_hero3d($d){echo'<section class="tgs-hero"><div class="tgs-viewer">';if($d['model'])echo'<model-viewer src="'.esc_url($d['model']).'" camera-controls auto-rotate shadow-intensity="1"></model-viewer>';elseif($d['thumb'])echo'<img src="'.esc_url($d['thumb']).'" alt="'.esc_attr(get_the_title()).'">';echo'</div><div class="tgs-heading"><span class="tgs-kicker">THE GAMER SHOP</span><h1>'.esc_html(get_the_title()).'</h1></div></section>';}
function tgs_sq_block_pricebox($d){$meta=$d['meta'];echo'<section class="tgs-summary"><h2>Tu equipo</h2><div class="tgs-price"><small>Transferencia</small><strong>'.wp_kses_post(wc_price(((int)$meta('_tgs_price_transfer_cents'))/100)).'</strong><span>Efectivo '.wp_kses_post(wc_price(((int)$meta('_tgs_price_cash_cents'))/100)).'</span></div>';woocommerce_template_single_add_to_cart();echo'</section>';}
function tgs_sq_block_addtocartsticky($d){echo'<div class="tgs-sticky" aria-hidden="true"><span>'.esc_html(get_the_title()).'</span><strong>'.wp_kses_post($d['product']->get_price_html()).'</strong><a href="'.esc_url($d['product']->add_to_cart_url()).'" class="button">Agregar al carrito</a></div>';}
function tgs_sq_layout_style($layout){$tokens=is_array($layout['tokens']??null)?$layout['tokens']:[];$accent=sanitize_hex_color($tokens['accent']??'')?:'#E31B23';$bg=sanitize_hex_color($tokens['bg']??'')?:'#080B12';$text=sanitize_hex_color($tokens['text']??'')?:'#F8FAFC';$radius=max(0,(float)($tokens['radius']??24));$font=str_replace([';',':','{','}','<','>'],'',sanitize_text_field($tokens['font']??'Inter, system-ui, sans-serif'));return'--tgs-accent:'.$accent.';--tgs-bg:'.$bg.';--tgs-text:'.$text.';--tgs-radius:'.$radius.'px;--tgs-font:'.$font.';';}

