<?php
defined('ABSPATH') || exit;
function tgs_sq_secret(){return defined('TGS_HMAC_SECRET')?TGS_HMAC_SECRET:(string)get_option('tgs_hmac_secret','');}
function tgs_sq_auth(WP_REST_Request $request){$secret=tgs_sq_secret();$provided=strtolower(trim((string)$request->get_header('X-TGS-Signature')));$expected=hash_hmac('sha256',$request->get_body(),$secret);return $secret!==''&&preg_match('/^[a-f0-9]{64}$/',$provided)&&hash_equals($expected,$provided);}
function tgs_sq_permission(WP_REST_Request $request){return tgs_sq_auth($request)?true:new WP_Error('tgs_unauthorized','Firma HMAC inválida',['status'=>401]);}
add_action('rest_api_init',function(){register_rest_route('tgs/v1','/ping',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>fn()=>['ok'=>true,'version'=>TGS_SQ_VERSION]]);register_rest_route('tgs/v1','/publish',['methods'=>'POST','permission_callback'=>'tgs_sq_permission','callback'=>'tgs_sq_publish']);register_rest_route('tgs/v1','/unpublish',['methods'=>'POST','permission_callback'=>'tgs_sq_permission','callback'=>'tgs_sq_unpublish']);});
function tgs_sq_find($external_id){$ids=get_posts(['post_type'=>'product','post_status'=>'any','fields'=>'ids','numberposts'=>1,'meta_key'=>'_tgs_external_id','meta_value'=>$external_id]);return $ids?(int)$ids[0]:0;}
function tgs_sq_publish(WP_REST_Request $request){if(!class_exists('WC_Product_Simple'))return new WP_Error('tgs_woo','WooCommerce no está activo',['status'=>503]);$p=$request->get_json_params();$external=sanitize_text_field($p['externalId']??'');if($external==='')return new WP_Error('tgs_payload','externalId es obligatorio',['status'=>400]);$id=tgs_sq_find($external);$product=$id?wc_get_product($id):new WC_Product_Simple();if(!$product)return new WP_Error('tgs_product','No se pudo cargar el producto',['status'=>500]);$product->set_name(sanitize_text_field($p['title']??'Presupuesto TGS'));$product->set_status('publish');$product->set_catalog_visibility('visible');$product->set_regular_price(wc_format_decimal(((int)($p['priceTransferCents']??0))/100,2));$product->set_manage_stock(false);$product->set_sku('TGS-'.substr(preg_replace('/[^A-Za-z0-9]/','',$external),0,24));if(!empty($p['slug']))$product->set_slug(sanitize_title($p['slug']));$id=$product->save();$term=term_exists('TGS','product_cat');if(!$term)$term=wp_insert_term('TGS','product_cat');if(!is_wp_error($term))wp_set_object_terms($id,[(int)(is_array($term)?$term['term_id']:$term)],'product_cat');$meta=['_tgs_external_id'=>$external,'_tgs_managed'=>'1','_tgs_model3d_url'=>esc_url_raw($p['model3dUrl']??''),'_tgs_thumbnail_url'=>esc_url_raw($p['thumbnailUrl']??''),'_tgs_gallery'=>wp_json_encode($p['gallery']??[]),'_tgs_price_list_cents'=>(string)(int)($p['priceListCents']??0),'_tgs_price_cash_cents'=>(string)(int)($p['priceCashCents']??0),'_tgs_price_transfer_cents'=>(string)(int)($p['priceTransferCents']??0),'_tgs_installments'=>wp_json_encode($p['installments']??[]),'_tgs_items'=>wp_json_encode($p['items']??[]),'_tgs_description_html'=>wp_kses_post($p['descriptionHtml']??''),'_tgs_power'=>wp_json_encode($p['power']??[]),'_tgs_games'=>wp_json_encode($p['games']??[]),'_tgs_compatibility'=>wp_json_encode($p['compatibility']??[]),'_tgs_layout'=>wp_json_encode($p['layout']??[])];foreach($meta as $key=>$value)update_post_meta($id,$key,$value);return['ok'=>true,'productId'=>$id,'url'=>get_permalink($id)];}
function tgs_sq_unpublish(WP_REST_Request $request){$external=sanitize_text_field(($request->get_json_params()['externalId']??''));$id=tgs_sq_find($external);if($id)wp_update_post(['ID'=>$id,'post_status'=>'draft']);return['ok'=>true,'productId'=>$id?:null];}
