import {BadRequestException,Body,ConflictException,Controller,Get,NotFoundException,Param,Post,Put,Query} from '@nestjs/common';
import {argon2id,hash} from 'argon2';
import {db} from '@tgs/database';
import {employeeCreateSchema,employeeCreateUserSchema,employeeLinkUserSchema,employeeRequestsQuerySchema,employeeUpdateSchema,idSchema,movementCreateSchema,movementsQuerySchema,movementUpdateSchema,obligationCreateSchema,paymentCreateSchema,periodConfirmSchema,periodParamSchema,salaryBulkApplySchema,salaryBulkPreviewSchema,salaryUpdateSchema,type EmployeeCreateInput,type EmployeeCreateUserInput,type EmployeeLinkUserInput,type EmployeeUpdateInput,type MovementCreateInput,type MovementsQuery,type MovementUpdateInput,type ObligationCreateInput,type PaymentCreateInput,type PeriodConfirmInput,type SalaryBulkApplyInput,type SalaryBulkPreviewInput,type SalaryUpdateInput} from '@tgs/contracts';
import {CurrentUser,jsonSafe,Roles,type RequestUser,ZodPipe} from './infrastructure.js';
import {addMonths,audit,balanceFrom,directionFor,employeeBalance,obligationPendingCents,reconcileAllocation,requireEmployee,salaryWithBps,splitInstallments} from './employees-service.js';

const currentSalary=(employeeId:string,tx:any=db)=>tx.salaryRecord.findFirst({where:{employeeId},orderBy:[{effectiveFrom:'desc'},{createdAt:'desc'}]});
const periodDates=(period:string)=>{const y=Number(period.slice(0,4)),m=Number(period.slice(4)),next=m===12?`${y+1}-01`:`${y}-${String(m+1).padStart(2,'0')}`;return{gte:new Date(`${y}-${String(m).padStart(2,'0')}-01T00:00:00-03:00`),lt:new Date(`${next}-01T00:00:00-03:00`)};};

/** Cachea el IPC más reciente (INDEC vía ArgentinaDatos) en memoria por 6hs para no pegarle a la API externa en cada apertura del modal. */
let ipcCache:{period:string|null;pct:number|null;fetchedAt:number}|null=null;
const IPC_CACHE_TTL_MS=6*60*60*1000;
async function fetchLatestIpc():Promise<{period:string|null;pct:number|null}>{
  if(ipcCache&&Date.now()-ipcCache.fetchedAt<IPC_CACHE_TTL_MS)return{period:ipcCache.period,pct:ipcCache.pct};
  try{
    const res=await fetch('https://api.argentinadatos.com/v1/finanzas/indices/inflacion');
    if(!res.ok)throw new Error(`IPC API status ${res.status}`);
    const rows=await res.json() as Array<{fecha:string;valor:number}>;
    const last=rows[rows.length-1];
    const result={period:last?last.fecha.slice(0,7):null,pct:last?last.valor:null};
    ipcCache={...result,fetchedAt:Date.now()};
    return result;
  }catch{
    return{period:null,pct:null};
  }
}

@Roles('ADMIN')
@Controller()
export class EmployeesController {
  @Get('employees') async list(){const employees=await db.employee.findMany({include:{branch:{select:{id:true,name:true}},salaryRecords:{take:1,orderBy:[{effectiveFrom:'desc'},{createdAt:'desc'}]},movements:{where:{status:{in:['APPLIED','PENDING']}},select:{status:true,direction:true,amountCents:true}}},orderBy:[{active:'desc'},{fullName:'asc'}]});return jsonSafe({items:employees.map(({movements,...e})=>({...e,balanceCents:balanceFrom(movements.filter(m=>m.status==='APPLIED')),pendingCount:movements.filter(m=>m.status==='PENDING').length}))});}

  @Get('employees/summary') async summary(){const [movements,pendingMovements,pendingRequests,employees]=await Promise.all([db.movement.findMany({where:{status:'APPLIED'},select:{direction:true,amountCents:true}}),db.movement.count({where:{status:'PENDING'}}),db.employeeRequest.count({where:{status:'PENDING_APPROVAL'}}),db.employee.count({where:{active:true}})]);const balances=new Map<string,bigint>();const grouped=await db.movement.findMany({where:{status:'APPLIED'},select:{employeeId:true,direction:true,amountCents:true}});for(const m of grouped)balances.set(m.employeeId,(balances.get(m.employeeId)??0n)+(m.direction==='COMPANY_OWES'?m.amountCents:-m.amountCents));return jsonSafe({activeEmployees:employees,totalCompanyOwesCents:[...balances.values()].filter(x=>x>0n).reduce((a,b)=>a+b,0n),totalEmployeesOweCents:-[...balances.values()].filter(x=>x<0n).reduce((a,b)=>a+b,0n),netBalanceCents:balanceFrom(movements),pendingMovements,pendingRequests});}

  @Get('employees/:id') async detail(@Param('id',new ZodPipe(idSchema))id:string){await requireEmployee(id);const [employee,balance,salary,pendingMovements,openObligations]=await Promise.all([db.employee.findUnique({where:{id},include:{branch:true,user:{select:{id:true,username:true,displayName:true,role:true,active:true}}}}),employeeBalance(id),currentSalary(id),db.movement.count({where:{employeeId:id,status:'PENDING'}}),db.obligation.count({where:{employeeId:id,status:'OPEN'}})]);return jsonSafe({...employee,balanceCents:balance,currentSalary:salary,summary:{pendingMovements,openObligations}});}

  @Post('employees') async create(@Body(new ZodPipe(employeeCreateSchema))body:EmployeeCreateInput,@CurrentUser()u:RequestUser){if(body.branchId&&!await db.branch.findUnique({where:{id:body.branchId}}))throw new BadRequestException('La sucursal seleccionada no existe');return jsonSafe(await db.$transaction(async tx=>{const e=await tx.employee.create({data:{...body,createdById:u.id}});await audit(tx,u.id,'Employee',e.id,'CREATE');return e;}));}
  @Put('employees/:id') async update(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(employeeUpdateSchema))body:EmployeeUpdateInput,@CurrentUser()u:RequestUser){await requireEmployee(id);if(body.branchId&&!await db.branch.findUnique({where:{id:body.branchId}}))throw new BadRequestException('La sucursal seleccionada no existe');return jsonSafe(await db.$transaction(async tx=>{const e=await tx.employee.update({where:{id},data:body});await audit(tx,u.id,'Employee',id,'UPDATE',{fields:Object.keys(body)});return e;}));}
  @Post('employees/:id/link-user') async linkUser(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(employeeLinkUserSchema))body:EmployeeLinkUserInput,@CurrentUser()u:RequestUser){await requireEmployee(id);if(!await db.user.findUnique({where:{id:body.userId}}))throw new NotFoundException('Usuario inexistente');try{return jsonSafe(await db.$transaction(async tx=>{const e=await tx.employee.update({where:{id},data:{userId:body.userId}});await audit(tx,u.id,'Employee',id,'LINK_USER',{userId:body.userId});return e;}));}catch(e:any){if(e?.code==='P2002')throw new ConflictException('Ese usuario ya está asociado a otro empleado');throw e;}}
  @Post('employees/:id/create-user') async createUser(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(employeeCreateUserSchema))body:EmployeeCreateUserInput,@CurrentUser()u:RequestUser){const employee=await requireEmployee(id);if(employee.userId)throw new ConflictException('El empleado ya tiene un usuario asociado');const passwordHash=await hash(body.password,{type:argon2id});try{return jsonSafe(await db.$transaction(async tx=>{const user=await tx.user.create({data:{username:body.username,passwordHash,displayName:body.displayName??employee.fullName,role:body.role??'VENDEDOR'}});await tx.employee.update({where:{id},data:{userId:user.id}});await audit(tx,u.id,'User',user.id,'CREATE',{employeeId:id});return{id:user.id,username:user.username,displayName:user.displayName,role:user.role,active:user.active};}));}catch(e:any){if(e?.code==='P2002')throw new ConflictException('Ese nombre de usuario ya existe');throw e;}}

  @Get('employees/:id/movements') async movements(@Param('id',new ZodPipe(idSchema))id:string,@Query(new ZodPipe(movementsQuerySchema))q:MovementsQuery){await requireEmployee(id);const dates=q.period?periodDates(q.period):undefined;return jsonSafe({items:await db.movement.findMany({where:{employeeId:id,status:q.status,kind:q.kind,direction:q.direction,occurredAt:dates},orderBy:[{occurredAt:'desc'},{createdAt:'desc'}]})});}
  @Get('employees/:id/balance') async balance(@Param('id',new ZodPipe(idSchema))id:string){await requireEmployee(id);return jsonSafe({employeeId:id,balanceCents:await employeeBalance(id)});}
  @Post('employees/:id/movements') async createMovement(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(movementCreateSchema))body:MovementCreateInput,@CurrentUser()u:RequestUser){await requireEmployee(id);return jsonSafe(await db.$transaction(async tx=>{const status=body.status??'PENDING',now=new Date();const movement=await tx.movement.create({data:{employeeId:id,kind:body.kind,direction:directionFor(body.kind,body.direction),amountCents:BigInt(body.amountCents),occurredAt:body.occurredAt??now,status,description:body.description??null,createdById:u.id,...(status==='APPLIED'?{appliedById:u.id,appliedAt:now}:{})}});await audit(tx,u.id,'Movement',movement.id,'CREATE');return movement;}));}
  @Put('movements/:id') async updateMovement(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(movementUpdateSchema))body:MovementUpdateInput,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.movement.findUnique({where:{id}});if(!old)throw new NotFoundException('Movimiento inexistente');if(old.status!=='PENDING')throw new BadRequestException('Solo se pueden editar movimientos pendientes');const kind=body.kind??old.kind;const movement=await tx.movement.update({where:{id},data:{...body,amountCents:body.amountCents?BigInt(body.amountCents):undefined,direction:body.direction??(body.kind?directionFor(kind):undefined),description:body.description!==undefined?body.description:undefined}});await audit(tx,u.id,'Movement',id,'UPDATE');return movement;}));}
  @Post('movements/:id/apply') async applyMovement(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.movement.findUnique({where:{id}});if(!old)throw new NotFoundException('Movimiento inexistente');if(old.status!=='PENDING')throw new BadRequestException('Solo se pueden aplicar movimientos pendientes');const movement=await tx.movement.update({where:{id},data:{status:'APPLIED',appliedById:u.id,appliedAt:new Date()}});await audit(tx,u.id,'Movement',id,'APPLY');return movement;}));}
  @Post('movements/:id/cancel') async cancelMovement(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.movement.findUnique({where:{id}});if(!old)throw new NotFoundException('Movimiento inexistente');if(old.status==='CANCELLED')throw new BadRequestException('El movimiento ya está cancelado');const movement=await tx.movement.update({where:{id},data:{status:'CANCELLED',cancelledById:u.id,cancelledAt:new Date()}});await audit(tx,u.id,'Movement',id,'CANCEL');return movement;}));}

  @Get('employees/:id/salary') async salary(@Param('id',new ZodPipe(idSchema))id:string){await requireEmployee(id);return jsonSafe(await currentSalary(id));}
  @Get('employees/:id/salary/history') async salaryHistory(@Param('id',new ZodPipe(idSchema))id:string){await requireEmployee(id);return jsonSafe({items:await db.salaryRecord.findMany({where:{employeeId:id},orderBy:[{effectiveFrom:'desc'},{createdAt:'desc'}]})});}
  /**
   * Cargar un sueldo también devenga ese monto en la cuenta corriente (movimiento SALARY_ACCRUAL,
   * COMPANY_OWES): así "neto a pagar" = cuenta corriente = sueldo devengado - deudas - lo ya pagado,
   * todo en un solo número que se acumula mes a mes si no se le paga completo (no arranca en cero).
   */
  @Put('employees/:id/salary') async setSalary(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(salaryUpdateSchema))body:SalaryUpdateInput,@CurrentUser()u:RequestUser){await requireEmployee(id);return jsonSafe(await db.$transaction(async tx=>{const old=await currentSalary(id,tx);const effectiveFrom=body.effectiveFrom??new Date();const record=await tx.salaryRecord.create({data:{employeeId:id,amountCents:BigInt(body.amountCents),effectiveFrom,previousAmountCents:old?.amountCents,changeBps:body.changeBps??null,reason:body.reason,createdById:u.id}});const now=new Date();await tx.movement.create({data:{employeeId:id,kind:'SALARY_ACCRUAL',direction:'COMPANY_OWES',amountCents:BigInt(body.amountCents),occurredAt:effectiveFrom,status:'APPLIED',description:body.reason?`Sueldo devengado — ${body.reason}`:'Sueldo devengado',salaryRecordId:record.id,createdById:u.id,appliedById:u.id,appliedAt:now}});await audit(tx,u.id,'SalaryRecord',record.id,'CREATE');return record;}));}
  @Get('employees/:id/salary/suggestion') async salarySuggestion(@Param('id',new ZodPipe(idSchema))id:string){await requireEmployee(id);const [old,ipc]=await Promise.all([currentSalary(id),fetchLatestIpc()]);const previousAmountCents=old?.amountCents??null;const suggestedAmountCents=previousAmountCents!=null&&ipc.pct!=null?BigInt(Math.round(Number(previousAmountCents)*(1+ipc.pct/100))):null;return jsonSafe({previousAmountCents,ipcPeriod:ipc.period,ipcPct:ipc.pct,suggestedAmountCents});}

  @Get('ipc/latest') async ipcLatest(){return jsonSafe(await fetchLatestIpc());}
  @Post('employees/salary/bulk-preview') async salaryPreview(@Body(new ZodPipe(salaryBulkPreviewSchema))body:SalaryBulkPreviewInput){const employees=await db.employee.findMany({where:{active:true,id:body.employeeIds?{in:body.employeeIds}:undefined},select:{id:true,fullName:true,salaryRecords:{take:1,orderBy:[{effectiveFrom:'desc'},{createdAt:'desc'}]}}});return jsonSafe({items:employees.filter(e=>e.salaryRecords[0]).map(e=>{const old=e.salaryRecords[0]!.amountCents;return{employeeId:e.id,name:e.fullName,oldCents:old,bps:body.bps,newCents:salaryWithBps(old,body.bps,body.roundingStepPesos)}})});}
  @Post('employees/salary/bulk-apply') async salaryApply(@Body(new ZodPipe(salaryBulkApplySchema))body:SalaryBulkApplyInput,@CurrentUser()u:RequestUser){if(new Set(body.items.map(i=>i.employeeId)).size!==body.items.length)throw new BadRequestException('No se puede repetir un empleado');return jsonSafe(await db.$transaction(async tx=>{const records=[];for(const item of body.items){await requireEmployee(item.employeeId,tx);const old=await currentSalary(item.employeeId,tx);if(!old)throw new BadRequestException('Todos los empleados deben tener un sueldo vigente');const record=await tx.salaryRecord.create({data:{employeeId:item.employeeId,amountCents:BigInt(item.newCents),effectiveFrom:new Date(),previousAmountCents:old.amountCents,changeBps:body.bps,reason:'Actualización salarial masiva',createdById:u.id}});records.push(record);}await audit(tx,u.id,'SalaryRecord','bulk','BULK_APPLY',{bps:body.bps,count:records.length});return{items:records};}));}

  @Get('employees/:id/obligations') async obligations(@Param('id',new ZodPipe(idSchema))id:string){await requireEmployee(id);const obligations=await db.obligation.findMany({where:{employeeId:id},select:{id:true,kind:true,originalAmountCents:true,description:true,productId:true,status:true,createdAt:true,installments:{select:{id:true,number:true,amountCents:true,period:true,status:true,paidCents:true},orderBy:{number:'asc'}}},orderBy:{createdAt:'desc'}});return jsonSafe({items:await Promise.all(obligations.map(async obligation=>({...obligation,pendingCents:await obligationPendingCents(db,obligation)})))});}
  @Post('employees/:id/obligations') async obligation(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(obligationCreateSchema))body:ObligationCreateInput,@CurrentUser()u:RequestUser){await requireEmployee(id);return jsonSafe(await db.$transaction(async tx=>{const total=BigInt(body.originalAmountCents);const obligation=await tx.obligation.create({data:{employeeId:id,kind:body.kind,originalAmountCents:total,description:body.description??null,productId:body.productId??null,createdById:u.id}});const now=new Date();await tx.movement.create({data:{employeeId:id,kind:body.kind==='OTHER'?'DEBT':body.kind,direction:'EMPLOYEE_OWES',amountCents:total,status:'APPLIED',occurredAt:now,description:body.description??null,obligationId:obligation.id,createdById:u.id,appliedById:u.id,appliedAt:now}});if(body.installments){const amounts=splitInstallments(total,body.installments.count,body.installments.amountsCents);await tx.installmentPlan.create({data:{obligationId:obligation.id,count:body.installments.count,firstPeriod:body.installments.firstPeriod}});await tx.installment.createMany({data:amounts.map((amountCents,i)=>({obligationId:obligation.id,number:i+1,amountCents,period:addMonths(body.installments!.firstPeriod,i)}))});}await audit(tx,u.id,'Obligation',obligation.id,'CREATE');return tx.obligation.findUnique({where:{id:obligation.id},include:{plan:true,installments:true,movements:true}});}));}
  @Get('obligations/:id') async getObligation(@Param('id',new ZodPipe(idSchema))id:string){const item=await db.obligation.findUnique({where:{id},include:{plan:true,installments:true,movements:true}});if(!item)throw new NotFoundException('Obligación inexistente');return jsonSafe(item);}
  @Post('obligations/:id/cancel') async cancelObligation(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.obligation.findUnique({where:{id}});if(!old)throw new NotFoundException('Obligación inexistente');if(old.status==='SETTLED')throw new BadRequestException('No se puede cancelar una obligación saldada');await tx.installment.updateMany({where:{obligationId:id,status:{not:'PAID'}},data:{status:'CANCELLED'}});await tx.movement.updateMany({where:{obligationId:id,status:{not:'CANCELLED'}},data:{status:'CANCELLED',cancelledById:u.id,cancelledAt:new Date()}});const next=await tx.obligation.update({where:{id},data:{status:'CANCELLED'}});await audit(tx,u.id,'Obligation',id,'CANCEL');return next;}));}

  @Post('employees/:id/payments') async payment(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(paymentCreateSchema))body:PaymentCreateInput,@CurrentUser()u:RequestUser){await requireEmployee(id);const total=BigInt(body.amountCents),allocated=(body.allocations??[]).reduce((s,a)=>s+BigInt(a.amountCents),0n);if(allocated>total)throw new BadRequestException('Las asignaciones no pueden superar el pago');return jsonSafe(await db.$transaction(async tx=>{const paidAt=body.paidAt??new Date();const payment=await tx.payment.create({data:{employeeId:id,amountCents:total,method:body.method,paidAt,reference:body.reference,createdById:u.id}});await tx.movement.create({data:{employeeId:id,kind:'SALARY_PAYMENT',direction:'EMPLOYEE_OWES',amountCents:total,status:'APPLIED',occurredAt:paidAt,description:body.reference,paymentId:payment.id,createdById:u.id,appliedById:u.id,appliedAt:new Date()}});for(const allocation of body.allocations??[]){const amount=BigInt(allocation.amountCents);await tx.paymentAllocation.create({data:{paymentId:payment.id,targetType:allocation.targetType,targetId:allocation.targetId,amountCents:amount}});await reconcileAllocation(tx,allocation.targetType,allocation.targetId,amount,id);}await audit(tx,u.id,'Payment',payment.id,'CREATE');return tx.payment.findUnique({where:{id:payment.id},include:{allocations:true,movements:true}});}));}

  @Get('employee-requests') async requests(@Query(new ZodPipe(employeeRequestsQuerySchema))q:{status?:any}){return jsonSafe({items:await db.employeeRequest.findMany({where:{status:q.status},include:{employee:{select:{id:true,fullName:true}}},orderBy:{createdAt:'desc'}})});}
  @Post('employee-requests/:id/approve') async approve(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const request=await tx.employeeRequest.findUnique({where:{id}});if(!request)throw new NotFoundException('Solicitud inexistente');if(request.status!=='PENDING_APPROVAL')throw new BadRequestException('La solicitud ya fue revisada');const now=new Date(),movement=await tx.movement.create({data:{employeeId:request.employeeId,kind:request.kind,direction:directionFor(request.kind),amountCents:request.amountCents,status:'APPLIED',occurredAt:now,description:request.description,requestId:id,createdById:u.id,appliedById:u.id,appliedAt:now}});const next=await tx.employeeRequest.update({where:{id},data:{status:'APPROVED',reviewedById:u.id,reviewedAt:now,resultingMovementId:movement.id}});await audit(tx,u.id,'EmployeeRequest',id,'APPROVE');return next;}));}
  @Post('employee-requests/:id/reject') async reject(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const request=await tx.employeeRequest.findUnique({where:{id}});if(!request)throw new NotFoundException('Solicitud inexistente');if(request.status!=='PENDING_APPROVAL')throw new BadRequestException('La solicitud ya fue revisada');const next=await tx.employeeRequest.update({where:{id},data:{status:'REJECTED',reviewedById:u.id,reviewedAt:new Date()}});await audit(tx,u.id,'EmployeeRequest',id,'REJECT');return next;}));}

  @Get('employees/:id/period/:period') async period(@Param('id',new ZodPipe(idSchema))id:string,@Param('period',new ZodPipe(periodParamSchema))period:string){await requireEmployee(id);const range=periodDates(period),salary=await currentSalary(id),[prior,installments,advances]=await Promise.all([db.movement.findMany({where:{employeeId:id,status:'APPLIED',occurredAt:{lt:range.gte}},select:{amountCents:true,direction:true}}),db.installment.findMany({where:{obligation:{employeeId:id,status:'OPEN'},period,status:{in:['PENDING','PARTIAL']}},include:{obligation:{select:{id:true,description:true}}}}),db.movement.findMany({where:{employeeId:id,kind:'ADVANCE',status:'APPLIED',occurredAt:range}})]);const salaryCents=salary?.amountCents??0n,previousBalanceCents=balanceFrom(prior),installmentsCents=installments.reduce((s,i)=>s+(i.amountCents-i.paidCents),0n),advancesCents=advances.reduce((s,m)=>s+m.amountCents,0n);return jsonSafe({employeeId:id,period,salaryCents,installments,advances,previousBalanceCents,netCents:salaryCents+previousBalanceCents-installmentsCents-advancesCents,persisted:false});}
  @Post('employees/:id/period/:period/confirm') async confirmPeriod(@Param('id',new ZodPipe(idSchema))id:string,@Param('period',new ZodPipe(periodParamSchema))period:string,@Body(new ZodPipe(periodConfirmSchema))body:PeriodConfirmInput,@CurrentUser()u:RequestUser){await requireEmployee(id);return jsonSafe(await db.$transaction(async tx=>{if(await tx.employeePeriod.findUnique({where:{employeeId_period:{employeeId:id,period}}}))throw new ConflictException('El período ya fue confirmado');const salary=await currentSalary(id,tx),now=new Date(),lines=[];for(const item of body.applied){const movement=await tx.movement.findUnique({where:{id:item.movementId}});if(!movement||movement.employeeId!==id)throw new BadRequestException('El movimiento no pertenece al empleado');if(movement.status!=='PENDING')throw new BadRequestException('Solo se pueden confirmar movimientos pendientes');lines.push(await tx.movement.update({where:{id:movement.id},data:{status:'APPLIED',appliedById:u.id,appliedAt:now}}));}const balance=await employeeBalance(id,tx);const saved=await tx.employeePeriod.create({data:{employeeId:id,period,baseSalaryCents:salary?.amountCents??0n,linesJson:jsonSafe(lines),netCents:(salary?.amountCents??0n)+balance,status:'CONFIRMED',confirmedById:u.id,confirmedAt:now}});await audit(tx,u.id,'EmployeePeriod',saved.id,'CONFIRM',{movementIds:body.applied.map(x=>x.movementId)});return saved;}));}
}
