import{BadGatewayException,BadRequestException,Body,Controller,Delete,Get,NotFoundException,Param,Patch,Post,Put,Query,Req,StreamableFile}from'@nestjs/common';
import{createHmac,randomUUID}from'node:crypto';import{createReadStream,existsSync}from'node:fs';import path from'node:path';import{z}from'zod';import{db,enqueueJob}from'@tgs/database';import{assetFromUrlSchema,assetModeSchema,assetUpdateSchema,DEFAULT_LANDING_LAYOUT,idSchema,landingLayoutSchema,quoteEnrichmentUpdateSchema,thumbnailGenerateSchema,thumbnailRulesSchema,thumbnailTemplateCreateSchema,thumbnailTemplateUpdateSchema,productContentSchema,quoteFamilyPublishSettingsSchema,type ProductContentInput,type QuoteFamilyPublishSettingsInput,type AssetFromUrlInput,type AssetModeInput,type AssetUpdateInput,type LandingLayout,type QuoteEnrichmentUpdateInput,type ThumbnailGenerateInput,type ThumbnailRules,type ThumbnailTemplateCreateInput,type ThumbnailTemplateUpdateInput}from'@tgs/contracts';import{buildPublishPayload,generateBackground,getHiggsfieldKey,getSerperKey,publishQuote,searchImages,WordpressPublishError}from'@tgs/providers';import{loadR2FromModuleConfig}from'@tgs/storage';import{AiTask,createAiClient,DEFAULT_AI_MODEL,describeOpenAiError,QuoteEnrichmentService,type AiCacheRepo}from'@tgs/ai';import{decryptSecret}from'@tgs/config';import{CurrentUser,jsonSafe,type RequestUser,ZodPipe}from'./infrastructure.js';import{renderThumbnail}from'./thumbnail-render.js';
const serperQuerySchema=z.object({q:z.string().trim().min(1).max(300)}).strict();
const audit=(tx:any,userId:string,entityId:string,action:string,previous:unknown,next:unknown,entityType='ProductAsset')=>tx.auditLog.create({data:{userId,entityType,entityId,action,previous:previous==null?null:jsonSafe(previous),next:next==null?null:jsonSafe(next)}});
const ext=(filename:string,mimetype:string)=>{const found=/\.([a-zA-Z0-9]{2,5})$/.exec(filename)?.[1]?.toLowerCase();if(found&&['png','jpg','jpeg','webp','gif'].includes(found))return found;return mimetype==='image/png'?'png':mimetype==='image/webp'?'webp':'jpg';};
const modelExt=(filename:string)=>/\.gltf$/i.test(filename)?'gltf':/\.glb$/i.test(filename)?'glb':null;
async function ownStorageKey(url:string){const config=await db.externalModuleConfig.findUnique({where:{id:'singleton'},select:{r2PublicBaseUrl:true}});const base=config?.r2PublicBaseUrl?.replace(/\/$/,'');return base&&url.startsWith(`${base}/`)?url.slice(base.length+1):null;}
async function requireProduct(id:string){if(!await db.product.findUnique({where:{id},select:{id:true}}))throw new NotFoundException('Producto inexistente');}
async function downloadBytes(url:string,label:string){const response=await fetch(url);if(!response.ok)throw new BadRequestException(`No se pudo descargar ${label} (HTTP ${response.status})`);return Buffer.from(await response.arrayBuffer());}
async function quoteVersion(id:string){const version=await db.quoteVersion.findUnique({where:{id},include:{items:{orderBy:{position:'asc'}},family:true}});if(!version)throw new NotFoundException('Versión de presupuesto inexistente');return version;}
const aiCache:AiCacheRepo={async findCached(task,inputHash){const row=await db.aiRequest.findFirst({where:{task:task as any,inputHash,success:true},orderBy:{createdAt:'desc'}});return row?{resultJson:row.resultJson,model:row.model}:null;},async save(record){await db.aiRequest.create({data:{task:record.task as any,model:record.model,inputHash:record.inputHash,entityType:record.entityType??null,entityId:record.entityId??null,success:record.success,error:record.error??null,durationMs:record.durationMs??null,usageJson:record.usageJson as any,costUsdCents:record.costUsdCents??0n,resultJson:record.resultJson as any}});}};
async function enrichmentService(){const settings=await db.aiSettings.findUniqueOrThrow({where:{id:'singleton'}});const key=settings.enabled?(settings.apiKeyEncrypted?decryptSecret(settings.apiKeyEncrypted):process.env.OPENAI_API_KEY):undefined;return new QuoteEnrichmentService({client:key?createAiClient({apiKey:key}):null,model:settings.model??DEFAULT_AI_MODEL,cache:aiCache});}
const PRODUCT_DESCRIPTION_SYSTEM='Sos redactor comercial de The Gamer Shop, Argentina. Redactá en español una descripción breve (1 a 2 oraciones, máximo 220 caracteres) de un componente de PC gamer para mostrar debajo de su nombre en una ficha de producto. Tono profesional y directo, sin emojis, sin inventar especificaciones numéricas que no te dieron, sin repetir el nombre completo del producto tal cual.';
async function generateProductDescription(productName:string):Promise<string>{const settings=await db.aiSettings.findUniqueOrThrow({where:{id:'singleton'}});if(!settings.enabled)throw new BadRequestException('La IA está desactivada. Activala en Ajustes → IA.');const key=settings.apiKeyEncrypted?decryptSecret(settings.apiKeyEncrypted):process.env.OPENAI_API_KEY;const client=createAiClient({apiKey:key});if(!client)throw new BadRequestException('Falta la API key de OpenAI. Cargala en Ajustes → IA.');const extra=settings.productDescriptionPrompt?.trim();const systemPrompt=extra?`${PRODUCT_DESCRIPTION_SYSTEM}\n\nInstrucciones adicionales definidas por el negocio (respetalas siempre que no contradigan las reglas anteriores): ${extra}`:PRODUCT_DESCRIPTION_SYSTEM;let completion;try{completion=await client.chat.completions.create({model:settings.model??DEFAULT_AI_MODEL,max_tokens:150,messages:[{role:'system',content:systemPrompt},{role:'user',content:`Componente: ${productName}`}]});}catch(error){const info=describeOpenAiError(error);throw new BadGatewayException(info.message);}const text=completion.choices[0]?.message?.content?.trim();if(!text)throw new BadGatewayException('La IA no devolvió una respuesta.');return text;}
const installmentTotal=(base:bigint,bps:number)=>(base*BigInt(10000+bps)+5000n)/10000n;
function enrichmentData(body:QuoteEnrichmentUpdateInput){return{descriptionHtml:body.descriptionHtml,powerWatts:body.powerWatts,recommendedPsuWatts:body.recommendedPsuWatts,powerNote:body.powerNote,gamesJson:body.games as any,programsJson:body.programs as any,compatibilityJson:body.compatibility as any};}
async function createAsset(productId:string,input:{url:string;origin:'UPLOAD'|'SERPER'|'OFFICIAL';mode:'remove-bg'|'as-is'},userId:string){
 await requireProduct(productId);return db.$transaction(async tx=>{const asset=await tx.productAsset.create({data:{productId,origin:input.origin,sourceUrl:input.url,url:input.mode==='as-is'?input.url:null,status:input.mode==='as-is'?'READY':'PENDING',approved:input.mode==='as-is'}});await audit(tx,userId,asset.id,'CREATE',null,asset);if(input.mode==='remove-bg')await enqueueJob('product-asset:remove-bg',{assetId:asset.id},{entityType:'ProductAsset',entityId:asset.id});return asset;});
}
function resolveWpPluginZip(){const candidates=[process.env.WP_PLUGIN_ZIP_PATH,path.resolve(process.cwd(),'wordpress-plugin/tgs-smart-quotes.zip'),path.resolve(process.cwd(),'../../wordpress-plugin/tgs-smart-quotes.zip'),path.resolve(process.cwd(),'storage/wordpress-plugin/tgs-smart-quotes.zip'),path.resolve(process.cwd(),'../../storage/wordpress-plugin/tgs-smart-quotes.zip')].filter((value):value is string=>Boolean(value));return candidates.find(existsSync)??null;}
function savedLandingLayout(value:unknown):LandingLayout{const parsed=landingLayoutSchema.safeParse(value);return parsed.success?parsed.data:DEFAULT_LANDING_LAYOUT;}
async function postWordpress(pathname:string,payload:unknown){const config=await db.externalModuleConfig.findUniqueOrThrow({where:{id:'singleton'}});if(!config.wpHmacSecretEnc)throw new BadRequestException('Configurá el secreto HMAC de WordPress');const body=JSON.stringify(jsonSafe(payload));const signature=createHmac('sha256',decryptSecret(config.wpHmacSecretEnc)).update(body).digest('hex');let response:Response;try{response=await fetch(`${config.wpBaseUrl.replace(/\/$/,'')}/wp-json/tgs/v1/${pathname}`,{method:'POST',headers:{'content-type':'application/json','X-TGS-Signature':signature},body});}catch{throw new BadGatewayException('No se pudo conectar con WordPress');}const text=await response.text();let result:any={};try{result=text?JSON.parse(text):{};}catch{}if(!response.ok)throw new BadGatewayException(result?.message??`WordPress respondió HTTP ${response.status}`);return result;}
@Controller('external-module')
export class ExternalModuleController{
 @Get('landing-layout')async landingLayout(){const config=await db.externalModuleConfig.findUnique({where:{id:'singleton'},select:{landingLayoutJson:true}});return jsonSafe(savedLandingLayout(config?.landingLayoutJson));}
 @Put('landing-layout')async updateLandingLayout(@Body(new ZodPipe(landingLayoutSchema))body:LandingLayout,@CurrentUser()u:RequestUser){const old=await db.externalModuleConfig.findUnique({where:{id:'singleton'},select:{landingLayoutJson:true}});const next=await db.$transaction(async tx=>{const saved=await tx.externalModuleConfig.upsert({where:{id:'singleton'},create:{id:'singleton',landingLayoutJson:body as any},update:{landingLayoutJson:body as any}});await audit(tx,u.id,'singleton','UPDATE_LAYOUT',old?.landingLayoutJson??null,body,'ExternalModuleConfig');return saved;});return jsonSafe(savedLandingLayout(next.landingLayoutJson));}
 @Get('products/:productId/assets')async list(@Param('productId',new ZodPipe(idSchema))productId:string){await requireProduct(productId);return jsonSafe(await db.productAsset.findMany({where:{productId},orderBy:[{isPrimary:'desc'},{createdAt:'desc'}]}));}
 @Post('products/:productId/assets/upload')async upload(@Param('productId',new ZodPipe(idSchema))productId:string,@Query(new ZodPipe(assetModeSchema))input:AssetModeInput,@Req()req:any,@CurrentUser()u:RequestUser){
  await requireProduct(productId);if(typeof req.file!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const part=await req.file();if(!part)throw new BadRequestException('Seleccioná una imagen');const mimetype=String(part.mimetype??'');if(!mimetype.startsWith('image/'))throw new BadRequestException('El archivo debe ser una imagen');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('La imagen está vacía');
  const key=`product-assets/${productId}/source-${randomUUID()}.${ext(String(part.filename??''),mimetype)}`;const stored=await(await loadR2FromModuleConfig()).put(key,buffer,mimetype);return jsonSafe(await createAsset(productId,{url:stored.url,origin:'UPLOAD',mode:input.mode},u.id));
 }
 @Post('products/:productId/assets/from-url')async fromUrl(@Param('productId',new ZodPipe(idSchema))productId:string,@Body(new ZodPipe(assetFromUrlSchema))input:AssetFromUrlInput,@CurrentUser()u:RequestUser){return jsonSafe(await createAsset(productId,{...input,origin:input.origin??'SERPER'},u.id));}
 @Put('products/:productId/content')async updateContent(@Param('productId',new ZodPipe(idSchema))productId:string,@Body(new ZodPipe(productContentSchema))body:ProductContentInput,@CurrentUser()u:RequestUser){await requireProduct(productId);return jsonSafe(await db.$transaction(async tx=>{const old=await tx.product.findUnique({where:{id:productId}});const next=await tx.product.update({where:{id:productId},data:{description:body.description}});await audit(tx,u.id,productId,'UPDATE_CONTENT',old,next,'Product');return next;}));}
 @Post('products/:productId/content/generate')async generateContent(@Param('productId',new ZodPipe(idSchema))productId:string,@CurrentUser()u:RequestUser){const product=await db.product.findUnique({where:{id:productId}});if(!product)throw new NotFoundException('Producto inexistente');const description=await generateProductDescription(product.name);return jsonSafe(await db.$transaction(async tx=>{const old=await tx.product.findUnique({where:{id:productId}});const next=await tx.product.update({where:{id:productId},data:{description}});await audit(tx,u.id,productId,'GENERATE_CONTENT',old,next,'Product');return next;}));}
 @Put('quote-families/:familyId/publish-settings')async updatePublishSettings(@Param('familyId',new ZodPipe(idSchema))familyId:string,@Body(new ZodPipe(quoteFamilyPublishSettingsSchema))body:QuoteFamilyPublishSettingsInput,@CurrentUser()u:RequestUser){const old=await db.quoteFamily.findUnique({where:{id:familyId}});if(!old)throw new NotFoundException('Presupuesto inexistente');const next=await db.$transaction(async tx=>{const saved=await tx.quoteFamily.update({where:{id:familyId},data:{autoRepublish:body.autoRepublish}});await audit(tx,u.id,familyId,'UPDATE_PUBLISH_SETTINGS',old,saved,'QuoteFamily');return saved;});return jsonSafe(next);}
 @Post('quote-families/:familyId/thumbnail')async uploadFamilyThumbnail(@Param('familyId',new ZodPipe(idSchema))familyId:string,@Req()req:any,@CurrentUser()u:RequestUser){const family=await db.quoteFamily.findUnique({where:{id:familyId}});if(!family)throw new NotFoundException('Presupuesto inexistente');if(typeof req.file!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const part=await req.file();if(!part)throw new BadRequestException('Selecciona una imagen');const mimetype=String(part.mimetype??'');if(!mimetype.startsWith('image/'))throw new BadRequestException('El archivo debe ser una imagen');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('La imagen esta vacia');const key=`quote-thumbnails/${familyId}/${randomUUID()}.${ext(String(part.filename??''),mimetype)}`;const stored=await(await loadR2FromModuleConfig()).put(key,buffer,mimetype);const next=await db.$transaction(async tx=>{const saved=await tx.quoteFamily.update({where:{id:familyId},data:{thumbnailUrl:stored.url}});await audit(tx,u.id,familyId,'UPDATE_THUMBNAIL',{thumbnailUrl:family.thumbnailUrl},saved,'QuoteFamily');return saved;});return jsonSafe(next);}
 // Sin este try/catch, cualquier fallo de Serper (key inválida, cuenta sin
 // crédito, timeout) sale como un 500 genérico "Internal server error" y el
 // detalle real que devuelve la API se pierde antes de llegar a la pantalla.
 @Get('serper/images')async images(@Query(new ZodPipe(serperQuerySchema))query:{q:string}){
  let key:string;
  try{key=await getSerperKey();}catch(error){throw new BadRequestException(error instanceof Error?error.message:'Falta configurar la API key de Serper');}
  try{return{images:await searchImages(query.q,key)};}catch(error){throw new BadGatewayException(error instanceof Error?error.message:'Serper no pudo buscar imágenes');}
 }
 @Post('assets/:id/remove-bg')async removeBg(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.productAsset.findUnique({where:{id}});if(!old)throw new NotFoundException('Imagen inexistente');if(!old.sourceUrl)throw new BadRequestException('La imagen no tiene origen');const next=await tx.productAsset.update({where:{id},data:{status:'PENDING'}});await enqueueJob('product-asset:remove-bg',{assetId:id},{entityType:'ProductAsset',entityId:id});await audit(tx,u.id,id,'REMOVE_BG',old,next);return next;}));}
 @Post('assets/:id/confirm-as-is')async asIs(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.productAsset.findUnique({where:{id}});if(!old)throw new NotFoundException('Imagen inexistente');if(!old.sourceUrl)throw new BadRequestException('La imagen no tiene origen');const next=await tx.productAsset.update({where:{id},data:{url:old.sourceUrl,approved:true,status:'READY'}});await audit(tx,u.id,id,'CONFIRM_AS_IS',old,next);return next;}));}
 @Patch('assets/:id')async update(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(assetUpdateSchema))body:AssetUpdateInput,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.productAsset.findUnique({where:{id}});if(!old)throw new NotFoundException('Imagen inexistente');if(body.isPrimary)await tx.productAsset.updateMany({where:{productId:old.productId,id:{not:id}},data:{isPrimary:false}});const next=await tx.productAsset.update({where:{id},data:body});await audit(tx,u.id,id,'UPDATE',old,next);return next;}));}
 @Delete('assets/:id')async delete(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){const asset=await db.productAsset.findUnique({where:{id}});if(!asset)throw new NotFoundException('Imagen inexistente');await db.$transaction(async tx=>{await tx.productAsset.delete({where:{id}});await audit(tx,u.id,id,'DELETE',asset,null);});if(asset.storageKey)try{await(await loadR2FromModuleConfig()).delete(asset.storageKey);}catch{}return{ok:true};}
 @Get('thumbnail-templates')async thumbnailTemplates(){return jsonSafe(await db.thumbnailTemplate.findMany({orderBy:[{active:'desc'},{createdAt:'desc'}]}));}
 @Post('thumbnail-templates')async createThumbnailTemplate(@Body(new ZodPipe(thumbnailTemplateCreateSchema))body:ThumbnailTemplateCreateInput,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const next=await tx.thumbnailTemplate.create({data:{name:body.name,rulesJson:body.rules as any}});await audit(tx,u.id,next.id,'CREATE',null,next,'ThumbnailTemplate');return next;}));}
 @Post('thumbnail-templates/:id/image')async uploadThumbnailTemplateImage(@Param('id',new ZodPipe(idSchema))id:string,@Req()req:any,@CurrentUser()u:RequestUser){const old=await db.thumbnailTemplate.findUnique({where:{id}});if(!old)throw new NotFoundException('Plantilla inexistente');if(typeof req.file!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const part=await req.file();if(!part)throw new BadRequestException('Seleccioná una imagen de plantilla');const mimetype=String(part.mimetype??'');if(!mimetype.startsWith('image/'))throw new BadRequestException('El archivo debe ser una imagen');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('La imagen está vacía');const storage=await loadR2FromModuleConfig();const stored=await storage.put(`thumbnail-templates/${id}/${randomUUID()}.${ext(String(part.filename??''),mimetype)}`,buffer,mimetype);const next=await db.$transaction(async tx=>{const saved=await tx.thumbnailTemplate.update({where:{id},data:{templateImageUrl:stored.url,templateKey:stored.key}});await audit(tx,u.id,id,'UPLOAD_IMAGE',old,saved,'ThumbnailTemplate');return saved;});if(old.templateKey)try{await storage.delete(old.templateKey);}catch{}return jsonSafe(next);}
 @Put('thumbnail-templates/:id')async updateThumbnailTemplate(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(thumbnailTemplateUpdateSchema))body:ThumbnailTemplateUpdateInput,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.thumbnailTemplate.findUnique({where:{id}});if(!old)throw new NotFoundException('Plantilla inexistente');const next=await tx.thumbnailTemplate.update({where:{id},data:{...(body.name!==undefined?{name:body.name}:{}),...(body.rules!==undefined?{rulesJson:body.rules as any}:{}),...(body.fonts!==undefined?{fontsJson:body.fonts as any}:{}),...(body.active!==undefined?{active:body.active}:{})}});await audit(tx,u.id,id,'UPDATE',old,next,'ThumbnailTemplate');return next;}));}
 @Delete('thumbnail-templates/:id')async deleteThumbnailTemplate(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){const old=await db.thumbnailTemplate.findUnique({where:{id}});if(!old)throw new NotFoundException('Plantilla inexistente');await db.$transaction(async tx=>{await tx.thumbnailTemplate.delete({where:{id}});await audit(tx,u.id,id,'DELETE',old,null,'ThumbnailTemplate');});if(old.templateKey)try{await(await loadR2FromModuleConfig()).delete(old.templateKey);}catch{}return{ok:true};}
 @Post('products/:productId/thumbnail')async generateThumbnail(@Param('productId',new ZodPipe(idSchema))productId:string,@Body(new ZodPipe(thumbnailGenerateSchema))body:ThumbnailGenerateInput){await requireProduct(productId);const[product,template,asset]=await Promise.all([db.product.findUnique({where:{id:productId},select:{name:true}}),db.thumbnailTemplate.findUnique({where:{id:body.templateId}}),db.productAsset.findFirst({where:{productId,status:'READY',url:{not:null}},orderBy:[{isPrimary:'desc'},{createdAt:'desc'}]})]);if(!template)throw new NotFoundException('Plantilla inexistente');if(!template.active)throw new BadRequestException('La plantilla está inactiva');if(!asset?.url)throw new BadRequestException('El producto no tiene una imagen principal lista');const parsed=thumbnailRulesSchema.safeParse(template.rulesJson);if(!parsed.success)throw new BadRequestException('Las reglas guardadas de la plantilla no son válidas');const rules:ThumbnailRules=parsed.data;const productBuffer=await downloadBytes(asset.url,'la imagen del producto');let backgroundBuffer:Buffer|null=null;let generatedBackground=false;if(body.useHiggsfield)try{backgroundBuffer=await generateBackground(body.higgsfieldPrompt??body.title??product?.name??'Fondo de producto tecnológico',{width:rules.width,height:rules.height},await getHiggsfieldKey());generatedBackground=true;}catch{}if(!backgroundBuffer&&template.templateImageUrl)backgroundBuffer=await downloadBytes(template.templateImageUrl,'la imagen de plantilla');const title=body.title??product?.name??'';const texts=rules.texts.map(text=>({value:text.source==='title'?title:text.value??'',x:text.x,y:text.y,fontSize:text.fontSize,color:text.color,...(text.fontFamily?{fontFamily:text.fontFamily}:{}),...(text.align?{align:text.align}:{})}));const renderRules=generatedBackground?{...rules,background:{type:'template' as const}}:rules;const output=await renderThumbnail({rules:renderRules,backgroundBuffer,productBuffer,texts});const stored=await(await loadR2FromModuleConfig()).put(`thumbnails/${productId}/${randomUUID()}.jpg`,output,'image/jpeg');return{url:stored.url};}
 @Get('products/:productId/case-model')async caseModel(@Param('productId',new ZodPipe(idSchema))productId:string){await requireProduct(productId);return jsonSafe(await db.caseModel3D.findUnique({where:{productId}}));}
 @Post('products/:productId/case-model/upload')async uploadCaseModel(@Param('productId',new ZodPipe(idSchema))productId:string,@Req()req:any,@CurrentUser()u:RequestUser){
  await requireProduct(productId);if(typeof req.file!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const part=await req.file();if(!part)throw new BadRequestException('Seleccioná un modelo GLB');const extension=modelExt(String(part.filename??''));if(!extension)throw new BadRequestException('El archivo debe tener extensión .glb o .gltf');const mimetype=String(part.mimetype??'').toLowerCase();const tolerated=['model/gltf-binary','model/gltf+json','application/octet-stream','application/gltf-buffer',''];if(!tolerated.includes(mimetype))throw new BadRequestException('El tipo de archivo no corresponde a un modelo GLB/GLTF');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('El modelo está vacío');
  const stored=await(await loadR2FromModuleConfig()).put(`case-models/${productId}/upload-${randomUUID()}.${extension}`,buffer,extension==='glb'?'model/gltf-binary':'model/gltf+json');const previous=await db.caseModel3D.findUnique({where:{productId}});const next=await db.$transaction(async tx=>{const saved=await tx.caseModel3D.upsert({where:{productId},create:{productId,source:'UPLOAD',glbUrl:stored.url,glbKey:stored.key,status:'READY',sourcePhotos:[]},update:{source:'UPLOAD',glbUrl:stored.url,glbKey:stored.key,status:'READY',sourcePhotos:[],tripoJobId:null}});await audit(tx,u.id,saved.id,'UPLOAD',previous,saved,'CaseModel3D');return saved;});return jsonSafe(next);
 }
 @Post('products/:productId/case-model/tripo')async tripoCaseModel(@Param('productId',new ZodPipe(idSchema))productId:string,@Req()req:any,@CurrentUser()u:RequestUser){
  await requireProduct(productId);if(typeof req.files!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const files:Array<{buffer:Buffer;extension:string;mimetype:string}>=[];for await(const part of req.files()){if(part.fieldname!=='photos')continue;const mimetype=String(part.mimetype??'');if(!mimetype.startsWith('image/'))throw new BadRequestException('Todos los archivos deben ser imágenes');if(files.length>=4)throw new BadRequestException('Podés subir hasta 4 fotos');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('Una de las fotos está vacía');files.push({buffer,extension:ext(String(part.filename??''),mimetype),mimetype});}if(files.length<1)throw new BadRequestException('Seleccioná entre 1 y 4 fotos');
  const storage=await loadR2FromModuleConfig();const urls:string[]=[];for(const file of files){const stored=await storage.put(`case-photos/${productId}/${randomUUID()}.${file.extension}`,file.buffer,file.mimetype);urls.push(stored.url);}const previous=await db.caseModel3D.findUnique({where:{productId}});const next=await db.$transaction(async tx=>{const saved=await tx.caseModel3D.upsert({where:{productId},create:{productId,source:'TRIPO',sourcePhotos:urls,status:'PENDING'},update:{source:'TRIPO',sourcePhotos:urls,status:'PENDING',glbUrl:null,glbKey:null,tripoJobId:null}});await audit(tx,u.id,saved.id,'GENERATE_TRIPO',previous,saved,'CaseModel3D');return saved;});await enqueueJob('case-model:tripo',{caseModelId:next.id},{entityType:'CaseModel3D',entityId:next.id});return jsonSafe(next);
 }
 @Delete('case-model/:id')async deleteCaseModel(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){const model=await db.caseModel3D.findUnique({where:{id}});if(!model)throw new NotFoundException('Modelo 3D inexistente');await db.$transaction(async tx=>{await tx.caseModel3D.delete({where:{id}});await audit(tx,u.id,id,'DELETE',model,null,'CaseModel3D');});try{const storage=await loadR2FromModuleConfig();const keys=(await Promise.all(model.sourcePhotos.map(ownStorageKey))).filter((key):key is string=>Boolean(key));if(model.glbKey)keys.push(model.glbKey);for(const key of new Set(keys))try{await storage.delete(key);}catch{}}catch{}return{ok:true};}
 @Get('wp-plugin/download')downloadWpPlugin(){const zip=resolveWpPluginZip();if(!zip)throw new NotFoundException('ZIP del plugin no encontrado. Ejecutá `pnpm wp-plugin:zip` en el servidor.');return new StreamableFile(createReadStream(zip),{type:'application/zip',disposition:'attachment; filename="tgs-smart-quotes.zip"'});}
 @Get('quotes/:versionId/publication')async publication(@Param('versionId',new ZodPipe(idSchema))versionId:string){await quoteVersion(versionId);return jsonSafe(await db.webPublication.findUnique({where:{quoteVersionId:versionId}}));}
 @Post('quotes/:versionId/publish')async publish(@Param('versionId',new ZodPipe(idSchema))versionId:string,@CurrentUser()u:RequestUser){const old=await db.webPublication.findUnique({where:{quoteVersionId:versionId}});try{const{webPublication}=await publishQuote(versionId);await db.$transaction(tx=>audit(tx,u.id,webPublication.id,'PUBLISH',old,webPublication,'WebPublication'));return jsonSafe(webPublication);}catch(error){if(error instanceof WordpressPublishError){if(error.httpStatus===400)throw new BadRequestException(error.message);if(error.httpStatus===404)throw new NotFoundException(error.message);throw new BadGatewayException(error.message);}throw error;}}
 @Post('quotes/:versionId/unpublish')async unpublish(@Param('versionId',new ZodPipe(idSchema))versionId:string,@CurrentUser()u:RequestUser){await quoteVersion(versionId);const old=await db.webPublication.findUnique({where:{quoteVersionId:versionId}});await postWordpress('unpublish',{externalId:versionId});// Se limpia tambien la `url`: al despublicar, la pagina deja de existir en
// WordPress, asi que conservarla dejaba el boton "Ver en la tienda"
// apuntando a un 404.
const next=await db.webPublication.upsert({where:{quoteVersionId:versionId},create:{quoteVersionId:versionId,status:'UNPUBLISHED'},update:{status:'UNPUBLISHED',lastError:null,url:null}});await db.$transaction(tx=>audit(tx,u.id,next.id,'UNPUBLISH',old,next,'WebPublication'));return jsonSafe(next);}
 @Get('quotes/:versionId/payload')async quotePayload(@Param('versionId',new ZodPipe(idSchema))versionId:string){const version=await quoteVersion(versionId);const company=await db.companySettings.findUniqueOrThrow({where:{id:'singleton'}});const activePlans=await db.financingPlan.findMany({where:{active:true},orderBy:{sortOrder:'asc'}});const snapshot=version.financingSnapshot;const plans=Array.isArray(snapshot)?snapshot:(snapshot&&typeof snapshot==='object'&&Array.isArray((snapshot as any).plans)?(snapshot as any).plans:activePlans);const list=installmentTotal(version.totalSaleCents,company.listInterestBps);return jsonSafe({externalId:version.id,visibleNumber:version.family.visibleNumber,version:version.version,items:version.items.map(item=>({name:item.frozenName,quantity:item.quantity,unitPriceCents:item.frozenSalePriceCents,subtotalCents:item.subtotalCents})),price:{listCents:list,cashCents:version.totalSaleCents,transferCents:version.totalSaleCents,currency:'ARS'},installmentPlans:plans.map((plan:any)=>{const total=installmentTotal(list,Number(plan.interestBps??0));return{bank:plan.bank??null,installments:Number(plan.installments),interestBps:Number(plan.interestBps??0),totalCents:total,installmentCents:(total+BigInt(Number(plan.installments))/2n)/BigInt(Number(plan.installments))};}),financingSnapshot:version.financingSnapshot});}
 // Payload exacto que se le manda a WordPress al publicar. La vista previa de
 // la app lo consume para mostrar lo que realmente se va a publicar (mismos
 // textos, precios, imagenes y tokens de diseno), en vez de una maqueta aparte.
 @Get('quotes/:versionId/publish-preview')async publishPreview(@Param('versionId',new ZodPipe(idSchema))versionId:string){await quoteVersion(versionId);try{return jsonSafe(await buildPublishPayload(versionId));}catch(error){if(error instanceof WordpressPublishError)throw new BadRequestException(error.message);throw error;}}
 @Get('quotes/:versionId/enrichment')async getEnrichment(@Param('versionId',new ZodPipe(idSchema))versionId:string){await quoteVersion(versionId);return jsonSafe(await db.quoteEnrichment.findUnique({where:{quoteVersionId:versionId}}));}
 @Post('quotes/:versionId/enrich')async enrichQuote(@Param('versionId',new ZodPipe(idSchema))versionId:string,@CurrentUser()u:RequestUser){const version=await quoteVersion(versionId);if(!version.items.length)throw new BadRequestException('El presupuesto no tiene ítems');const items=version.items.map(item=>({name:item.frozenName,quantity:item.quantity}));const aiSettings=await db.aiSettings.findUniqueOrThrow({where:{id:'singleton'}});const {result,metadata}=await(await enrichmentService()).enrich({items},{entity:{entityType:'QuoteVersion',entityId:versionId}},aiSettings.pcDescriptionPrompt);const old=await db.quoteEnrichment.findUnique({where:{quoteVersionId:versionId}});const next=await db.$transaction(async tx=>{const saved=await tx.quoteEnrichment.upsert({where:{quoteVersionId:versionId},create:{quoteVersionId:versionId,descriptionHtml:result.descriptionHtml,gamesJson:result.games,programsJson:result.programs,compatibilityJson:result.compatibility},update:{descriptionHtml:result.descriptionHtml,gamesJson:result.games,programsJson:result.programs,compatibilityJson:result.compatibility}});await audit(tx,u.id,saved.id,'GENERATE',old,saved,'QuoteEnrichment');return saved;});return jsonSafe({...next,ai:{usedAi:metadata.usedAi,cacheHit:metadata.cacheHit,model:metadata.model}});}
 @Put('quotes/:versionId/enrichment')async updateEnrichment(@Param('versionId',new ZodPipe(idSchema))versionId:string,@Body(new ZodPipe(quoteEnrichmentUpdateSchema))body:QuoteEnrichmentUpdateInput,@CurrentUser()u:RequestUser){await quoteVersion(versionId);const old=await db.quoteEnrichment.findUnique({where:{quoteVersionId:versionId}});const data=enrichmentData(body);const next=await db.$transaction(async tx=>{const saved=await tx.quoteEnrichment.upsert({where:{quoteVersionId:versionId},create:{quoteVersionId:versionId,...data},update:data});await audit(tx,u.id,saved.id,'UPDATE',old,saved,'QuoteEnrichment');return saved;});return jsonSafe(next);}
}
