import{BadRequestException,Body,Controller,Delete,Get,NotFoundException,Param,Patch,Post,Query,Req}from'@nestjs/common';
import{randomUUID}from'node:crypto';import{z}from'zod';import{db,enqueueJob}from'@tgs/database';import{assetFromUrlSchema,assetModeSchema,assetUpdateSchema,idSchema,type AssetFromUrlInput,type AssetModeInput,type AssetUpdateInput}from'@tgs/contracts';import{getSerperKey,searchImages}from'@tgs/providers';import{loadR2FromModuleConfig}from'@tgs/storage';import{CurrentUser,jsonSafe,type RequestUser,ZodPipe}from'./infrastructure.js';
const serperQuerySchema=z.object({q:z.string().trim().min(1).max(300)}).strict();
const audit=(tx:any,userId:string,entityId:string,action:string,previous:unknown,next:unknown,entityType='ProductAsset')=>tx.auditLog.create({data:{userId,entityType,entityId,action,previous:previous==null?null:jsonSafe(previous),next:next==null?null:jsonSafe(next)}});
const ext=(filename:string,mimetype:string)=>{const found=/\.([a-zA-Z0-9]{2,5})$/.exec(filename)?.[1]?.toLowerCase();if(found&&['png','jpg','jpeg','webp','gif'].includes(found))return found;return mimetype==='image/png'?'png':mimetype==='image/webp'?'webp':'jpg';};
const modelExt=(filename:string)=>/\.gltf$/i.test(filename)?'gltf':/\.glb$/i.test(filename)?'glb':null;
async function ownStorageKey(url:string){const config=await db.externalModuleConfig.findUnique({where:{id:'singleton'},select:{r2PublicBaseUrl:true}});const base=config?.r2PublicBaseUrl?.replace(/\/$/,'');return base&&url.startsWith(`${base}/`)?url.slice(base.length+1):null;}
async function requireProduct(id:string){if(!await db.product.findUnique({where:{id},select:{id:true}}))throw new NotFoundException('Producto inexistente');}
async function createAsset(productId:string,input:{url:string;origin:'UPLOAD'|'SERPER'|'OFFICIAL';mode:'remove-bg'|'as-is'},userId:string){
 await requireProduct(productId);return db.$transaction(async tx=>{const asset=await tx.productAsset.create({data:{productId,origin:input.origin,sourceUrl:input.url,url:input.mode==='as-is'?input.url:null,status:input.mode==='as-is'?'READY':'PENDING',approved:input.mode==='as-is'}});await audit(tx,userId,asset.id,'CREATE',null,asset);if(input.mode==='remove-bg')await enqueueJob('product-asset:remove-bg',{assetId:asset.id},{entityType:'ProductAsset',entityId:asset.id});return asset;});
}
@Controller('external-module')
export class ExternalModuleController{
 @Get('products/:productId/assets')async list(@Param('productId',new ZodPipe(idSchema))productId:string){await requireProduct(productId);return jsonSafe(await db.productAsset.findMany({where:{productId},orderBy:[{isPrimary:'desc'},{createdAt:'desc'}]}));}
 @Post('products/:productId/assets/upload')async upload(@Param('productId',new ZodPipe(idSchema))productId:string,@Query(new ZodPipe(assetModeSchema))input:AssetModeInput,@Req()req:any,@CurrentUser()u:RequestUser){
  await requireProduct(productId);if(typeof req.file!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const part=await req.file();if(!part)throw new BadRequestException('Seleccioná una imagen');const mimetype=String(part.mimetype??'');if(!mimetype.startsWith('image/'))throw new BadRequestException('El archivo debe ser una imagen');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('La imagen está vacía');
  const key=`product-assets/${productId}/source-${randomUUID()}.${ext(String(part.filename??''),mimetype)}`;const stored=await(await loadR2FromModuleConfig()).put(key,buffer,mimetype);return jsonSafe(await createAsset(productId,{url:stored.url,origin:'UPLOAD',mode:input.mode},u.id));
 }
 @Post('products/:productId/assets/from-url')async fromUrl(@Param('productId',new ZodPipe(idSchema))productId:string,@Body(new ZodPipe(assetFromUrlSchema))input:AssetFromUrlInput,@CurrentUser()u:RequestUser){return jsonSafe(await createAsset(productId,{...input,origin:input.origin??'SERPER'},u.id));}
 @Get('serper/images')async images(@Query(new ZodPipe(serperQuerySchema))query:{q:string}){return{images:await searchImages(query.q,await getSerperKey())};}
 @Post('assets/:id/remove-bg')async removeBg(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.productAsset.findUnique({where:{id}});if(!old)throw new NotFoundException('Imagen inexistente');if(!old.sourceUrl)throw new BadRequestException('La imagen no tiene origen');const next=await tx.productAsset.update({where:{id},data:{status:'PENDING'}});await enqueueJob('product-asset:remove-bg',{assetId:id},{entityType:'ProductAsset',entityId:id});await audit(tx,u.id,id,'REMOVE_BG',old,next);return next;}));}
 @Post('assets/:id/confirm-as-is')async asIs(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.productAsset.findUnique({where:{id}});if(!old)throw new NotFoundException('Imagen inexistente');if(!old.sourceUrl)throw new BadRequestException('La imagen no tiene origen');const next=await tx.productAsset.update({where:{id},data:{url:old.sourceUrl,approved:true,status:'READY'}});await audit(tx,u.id,id,'CONFIRM_AS_IS',old,next);return next;}));}
 @Patch('assets/:id')async update(@Param('id',new ZodPipe(idSchema))id:string,@Body(new ZodPipe(assetUpdateSchema))body:AssetUpdateInput,@CurrentUser()u:RequestUser){return jsonSafe(await db.$transaction(async tx=>{const old=await tx.productAsset.findUnique({where:{id}});if(!old)throw new NotFoundException('Imagen inexistente');if(body.isPrimary)await tx.productAsset.updateMany({where:{productId:old.productId,id:{not:id}},data:{isPrimary:false}});const next=await tx.productAsset.update({where:{id},data:body});await audit(tx,u.id,id,'UPDATE',old,next);return next;}));}
 @Delete('assets/:id')async delete(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){const asset=await db.productAsset.findUnique({where:{id}});if(!asset)throw new NotFoundException('Imagen inexistente');await db.$transaction(async tx=>{await tx.productAsset.delete({where:{id}});await audit(tx,u.id,id,'DELETE',asset,null);});if(asset.storageKey)try{await(await loadR2FromModuleConfig()).delete(asset.storageKey);}catch{}return{ok:true};}
 @Get('products/:productId/case-model')async caseModel(@Param('productId',new ZodPipe(idSchema))productId:string){await requireProduct(productId);return jsonSafe(await db.caseModel3D.findUnique({where:{productId}}));}
 @Post('products/:productId/case-model/upload')async uploadCaseModel(@Param('productId',new ZodPipe(idSchema))productId:string,@Req()req:any,@CurrentUser()u:RequestUser){
  await requireProduct(productId);if(typeof req.file!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const part=await req.file();if(!part)throw new BadRequestException('Seleccioná un modelo GLB');const extension=modelExt(String(part.filename??''));if(!extension)throw new BadRequestException('El archivo debe tener extensión .glb o .gltf');const mimetype=String(part.mimetype??'').toLowerCase();const tolerated=['model/gltf-binary','model/gltf+json','application/octet-stream','application/gltf-buffer',''];if(!tolerated.includes(mimetype))throw new BadRequestException('El tipo de archivo no corresponde a un modelo GLB/GLTF');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('El modelo está vacío');
  const stored=await(await loadR2FromModuleConfig()).put(`case-models/${productId}/upload-${randomUUID()}.${extension}`,buffer,extension==='glb'?'model/gltf-binary':'model/gltf+json');const previous=await db.caseModel3D.findUnique({where:{productId}});const next=await db.$transaction(async tx=>{const saved=await tx.caseModel3D.upsert({where:{productId},create:{productId,source:'UPLOAD',glbUrl:stored.url,glbKey:stored.key,status:'READY',sourcePhotos:[]},update:{source:'UPLOAD',glbUrl:stored.url,glbKey:stored.key,status:'READY',sourcePhotos:[],tripoJobId:null}});await audit(tx,u.id,saved.id,'UPLOAD',previous,saved,'CaseModel3D');return saved;});return jsonSafe(next);
 }
 @Post('products/:productId/case-model/tripo')async tripoCaseModel(@Param('productId',new ZodPipe(idSchema))productId:string,@Req()req:any,@CurrentUser()u:RequestUser){
  await requireProduct(productId);if(typeof req.files!=='function')throw new BadRequestException('Upload multipart no disponible en el servidor');const files:Array<{buffer:Buffer;extension:string;mimetype:string}>=[];for await(const part of req.files()){if(part.fieldname!=='photos')continue;const mimetype=String(part.mimetype??'');if(!mimetype.startsWith('image/'))throw new BadRequestException('Todos los archivos deben ser imágenes');if(files.length>=4)throw new BadRequestException('Podés subir hasta 4 fotos');const buffer=await part.toBuffer();if(!buffer.length)throw new BadRequestException('Una de las fotos está vacía');files.push({buffer,extension:ext(String(part.filename??''),mimetype),mimetype});}if(files.length<1)throw new BadRequestException('Seleccioná entre 1 y 4 fotos');
  const storage=await loadR2FromModuleConfig();const urls:string[]=[];for(const file of files){const stored=await storage.put(`case-photos/${productId}/${randomUUID()}.${file.extension}`,file.buffer,file.mimetype);urls.push(stored.url);}const previous=await db.caseModel3D.findUnique({where:{productId}});const next=await db.$transaction(async tx=>{const saved=await tx.caseModel3D.upsert({where:{productId},create:{productId,source:'TRIPO',sourcePhotos:urls,status:'PENDING'},update:{source:'TRIPO',sourcePhotos:urls,status:'PENDING',glbUrl:null,glbKey:null,tripoJobId:null}});await audit(tx,u.id,saved.id,'GENERATE_TRIPO',previous,saved,'CaseModel3D');return saved;});await enqueueJob('case-model:tripo',{caseModelId:next.id},{entityType:'CaseModel3D',entityId:next.id});return jsonSafe(next);
 }
 @Delete('case-model/:id')async deleteCaseModel(@Param('id',new ZodPipe(idSchema))id:string,@CurrentUser()u:RequestUser){const model=await db.caseModel3D.findUnique({where:{id}});if(!model)throw new NotFoundException('Modelo 3D inexistente');await db.$transaction(async tx=>{await tx.caseModel3D.delete({where:{id}});await audit(tx,u.id,id,'DELETE',model,null,'CaseModel3D');});try{const storage=await loadR2FromModuleConfig();const keys=(await Promise.all(model.sourcePhotos.map(ownStorageKey))).filter((key):key is string=>Boolean(key));if(model.glbKey)keys.push(model.glbKey);for(const key of new Set(keys))try{await storage.delete(key);}catch{}}catch{}return{ok:true};}
}
