import{ArgumentsHost,BadRequestException,CanActivate,Catch,createParamDecorator,ExecutionContext,ExceptionFilter,HttpException,Inject,Injectable,Logger,SetMetadata,UnauthorizedException}from'@nestjs/common';import{Reflector}from'@nestjs/core';import{createHash}from'node:crypto';import{db,type User}from'@tgs/database';import type{ZodType}from'zod';
export const SESSION_COOKIE='tgs_session';
// Switch automático: la cookie es Secure salvo en desarrollo, porque el navegador descarta
// cookies Secure sobre http. `COOKIE_SECURE` (true|false) es un override explícito opcional;
// sin esa variable, cualquier entorno distinto de development (producción, staging) usa Secure.
export const secureCookies=()=>{const forced=process.env.COOKIE_SECURE;if(forced==='true')return true;if(forced==='false')return false;return process.env.NODE_ENV!=='development';};
export const buildSessionCookie=(token:string,maxAgeSeconds:number)=>`${SESSION_COOKIE}=${token}; Max-Age=${maxAgeSeconds}; Path=/; HttpOnly${secureCookies()?'; Secure':''}; SameSite=Lax`;export const Public=()=>SetMetadata('public',true);export type RequestUser=Pick<User,'id'|'username'|'displayName'>;export const CurrentUser=createParamDecorator((_d:unknown,ctx:ExecutionContext)=>(ctx.switchToHttp().getRequest() as{user:RequestUser}).user);
export class ZodPipe{constructor(private schema:ZodType){}transform(value:unknown){const r=this.schema.safeParse(value);if(!r.success)throw new BadRequestException(r.error.issues.map(i=>i.message).join('; '));return r.data}}
// `@Inject(Reflector)` explícito: el runner de desarrollo (esbuild/tsx) no emite
// metadata de decoradores, así que la inyección por tipo dejaba el reflector en undefined.
@Injectable()export class AuthGuard implements CanActivate{constructor(@Inject(Reflector)private reflector:Reflector){}async canActivate(ctx:ExecutionContext){if(this.reflector.getAllAndOverride<boolean>('public',[ctx.getHandler(),ctx.getClass()]))return true;const req=ctx.switchToHttp().getRequest() as any,cookie=String(req.headers?.cookie??''),token=cookie.split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith(SESSION_COOKIE+'='))?.slice(SESSION_COOKIE.length+1);if(!token)throw new UnauthorizedException('Sesión requerida');const tokenHash=createHash('sha256').update(token).digest('hex'),session=await db.session.findUnique({where:{tokenHash},include:{user:true}});if(!session||session.expiresAt<=new Date()||!session.user.active){if(session)await db.session.delete({where:{id:session.id}}).catch(()=>undefined);throw new UnauthorizedException('Sesión inválida o vencida')}req.user={id:session.user.id,username:session.user.username,displayName:session.user.displayName};req.sessionId=session.id;const ttl=Number(process.env.SESSION_TTL_DAYS??7)*86400000,threshold=ttl*Number(process.env.SESSION_RENEWAL_PERCENT??25)/100;if(session.expiresAt.getTime()-Date.now()<threshold)await db.session.update({where:{id:session.id},data:{expiresAt:new Date(Date.now()+ttl),renewedAt:new Date()}});return true}}
@Catch()export class SpanishExceptionFilter implements ExceptionFilter{private log=new Logger('HTTP');catch(error:unknown,host:ArgumentsHost){const response=host.switchToHttp().getResponse(),request=host.switchToHttp().getRequest();const status=error instanceof HttpException?error.getStatus():500,raw=error instanceof HttpException?error.getResponse():null,message=typeof raw==='string'?raw:raw&&typeof raw==='object'&&'message'in raw?Array.isArray((raw as any).message)?(raw as any).message.join('; '):String((raw as any).message):'Ocurrió un error interno';if(status>=500)this.log.error(JSON.stringify({event:'http_error',method:request.method,url:request.url,status,error:error instanceof Error?error.message:String(error)}));response.status(status).send({error:status===400?'SOLICITUD_INVALIDA':status===401?'NO_AUTORIZADO':status===404?'NO_ENCONTRADO':status===429?'LIMITE_EXCEDIDO':'ERROR_INTERNO',message})}}
export const jsonSafe=(v:unknown)=>JSON.parse(JSON.stringify(v,(_k,x)=>typeof x==='bigint'?x.toString():x));

@Injectable()export class RateLimitGuard implements CanActivate{private readonly hits=new Map<string,number[]>();canActivate(ctx:ExecutionContext){const req=ctx.switchToHttp().getRequest() as any,key=String(req.ip??'unknown'),now=Date.now(),ttl=Number(process.env.THROTTLE_TTL_MS??60000),limit=Number(process.env.THROTTLE_LIMIT??100),recent=(this.hits.get(key)??[]).filter(x=>x>now-ttl);if(recent.length>=limit)throw new HttpException('Demasiadas solicitudes',429);recent.push(now);this.hits.set(key,recent);return true}}


