'use client';

import {FormEvent,useEffect,useState} from 'react';
import {api,apiUpload} from '../lib/api';
import {Alert,Checkbox,Field,Loading,PageHeader,Pill,Tabs,errorMessage} from './shared';

type Tab='conexiones'|'imagenes'|'modelo3d'|'plantillas'|'layout'|'almacenamiento';
type Provider='photoroom'|'tripo'|'higgsfield'|'serper'|'r2'|'wordpress';
type View={id:'singleton';photoroomKeySet:boolean;tripoKeySet:boolean;higgsfieldKeySet:boolean;higgsfieldSecretSet:boolean;serperKeySet:boolean;r2SecretAccessKeySet:boolean;wpHmacSecretSet:boolean;r2Endpoint:string|null;r2Bucket:string|null;r2AccessKeyId:string|null;r2PublicBaseUrl:string|null;wpBaseUrl:string;autoRepublish:boolean;updatedAt:string};
type Draft={photoroomKey:string;tripoKey:string;higgsfieldKey:string;higgsfieldSecret:string;serperKey:string;r2SecretAccessKey:string;wpHmacSecret:string;r2Endpoint:string;r2Bucket:string;r2AccessKeyId:string;r2PublicBaseUrl:string;wpBaseUrl:string;autoRepublish:boolean};
type Secret=keyof Pick<Draft,'photoroomKey'|'tripoKey'|'higgsfieldKey'|'higgsfieldSecret'|'serperKey'|'r2SecretAccessKey'|'wpHmacSecret'>;
const tabs:{id:Tab;label:string}[]=[{id:'conexiones',label:'Conexiones'},{id:'imagenes',label:'Imágenes'},{id:'modelo3d',label:'Modelo 3D'},{id:'plantillas',label:'Plantillas'},{id:'layout',label:'Layout de landing'},{id:'almacenamiento',label:'Almacenamiento'}];
const empty:Draft={photoroomKey:'',tripoKey:'',higgsfieldKey:'',higgsfieldSecret:'',serperKey:'',r2SecretAccessKey:'',wpHmacSecret:'',r2Endpoint:'',r2Bucket:'',r2AccessKeyId:'',r2PublicBaseUrl:'',wpBaseUrl:'https://www.thegamershop.com.ar',autoRepublish:true};

export function ModuloExternoView(){
 const[tab,setTab]=useState<Tab>('conexiones'),[view,setView]=useState<View|null>(null),[draft,setDraft]=useState<Draft>(empty);
 const[clears,setClears]=useState<Partial<Record<Secret,boolean>>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[testing,setTesting]=useState<Provider|null>(null);
 const[results,setResults]=useState<Partial<Record<Provider,{ok:boolean;detail?:string}>>>({});
 const load=async()=>{setLoading(true);setError(null);try{const v=await api<View>('/settings/external-module/config');setView(v);setDraft({...empty,r2Endpoint:v.r2Endpoint??'',r2Bucket:v.r2Bucket??'',r2AccessKeyId:v.r2AccessKeyId??'',r2PublicBaseUrl:v.r2PublicBaseUrl??'',wpBaseUrl:v.wpBaseUrl,autoRepublish:v.autoRepublish});}catch(e){setError(errorMessage(e));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const set=(key:keyof Draft,value:string|boolean)=>setDraft(d=>({...d,[key]:value}));
 const secret=(key:Secret,label:string,isSet:boolean)=><Field label={label} hint={isSet?'Hay una credencial cifrada guardada.':''}><input type={'password'} value={draft[key] as string} placeholder={isSet?'•••• guardada':'Ingresar credencial'} onChange={e=>set(key,e.target.value)}/>{isSet?<Checkbox label={'Borrar credencial guardada'} checked={Boolean(clears[key])} onChange={v=>setClears(c=>({...c,[key]:v}))}/>:null}</Field>;
 const test=async(provider:Provider)=>{setTesting(provider);setError(null);try{const r=await api<{ok:boolean;detail?:string}>(`/settings/external-module/config/test/${provider}`,{method:'POST'});setResults(x=>({...x,[provider]:r}));}catch(e){setResults(x=>({...x,[provider]:{ok:false,detail:errorMessage(e)}}));}finally{setTesting(null);}};
 const provider=(name:string,id:Provider,children:React.ReactNode)=>{const r=results[id];return <section className={'card card-pad'}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><h3 className={'panel-title'}>{name}</h3><button type={'button'} className={'btn-ghost btn-sm'} disabled={testing===id} onClick={()=>void test(id)}>{testing===id?'Probando…':'Probar'}</button></div>{children}{r?<Alert tone={r.ok?'ok':'error'}>{r.ok?'Conexión correcta':r.detail??'No se pudo conectar'}</Alert>:null}</section>};
 const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError(null);setNotice(null);try{const body={...draft,clearPhotoroomKey:clears.photoroomKey,clearTripoKey:clears.tripoKey,clearHiggsfieldKey:clears.higgsfieldKey,clearHiggsfieldSecret:clears.higgsfieldSecret,clearSerperKey:clears.serperKey,clearR2SecretAccessKey:clears.r2SecretAccessKey,clearWpHmacSecret:clears.wpHmacSecret};const next=await api<View>('/settings/external-module/config',{method:'PUT',body});setView(next);setDraft(d=>({...d,photoroomKey:'',tripoKey:'',higgsfieldKey:'',higgsfieldSecret:'',serperKey:'',r2SecretAccessKey:'',wpHmacSecret:''}));setClears({});setNotice('Configuración guardada.');}catch(e){setError(errorMessage(e));}finally{setSaving(false);}};
 return <div><PageHeader eyebrow={'Módulo Externo'} title={'Módulo Externo'} subtitle={'Configuración de conexiones y proveedores.'} actions={<Pill tone={'warn'}>Beta</Pill>}/><Tabs tabs={tabs} active={tab} onChange={setTab}/>{tab==='imagenes'?<ImagesTab/>:tab==='modelo3d'?<CaseModelTab/>:tab!=='conexiones'?<div className={'card card-pad'} style={{marginTop:20}}><h3 className={'panel-title'}>En construcción</h3></div>:loading?<Loading label={'Cargando conexiones…'}/>:<form onSubmit={save} style={{display:'grid',gap:16,marginTop:20}}>{error?<Alert>{error}</Alert>:null}{notice?<Alert tone={'ok'}>{notice}</Alert>:null}
 {provider('Photoroom','photoroom',secret('photoroomKey','API key',Boolean(view?.photoroomKeySet)))}
 {provider('Tripo','tripo',secret('tripoKey','API key',Boolean(view?.tripoKeySet)))}
 {provider('Higgsfield','higgsfield',<div className={'form-grid'}>{secret('higgsfieldKey','API key',Boolean(view?.higgsfieldKeySet))}{secret('higgsfieldSecret','API secret',Boolean(view?.higgsfieldSecretSet))}</div>)}
 {provider('Serper','serper',secret('serperKey','API key',Boolean(view?.serperKeySet)))}
 {provider('Cloudflare R2','r2',<div className={'form-grid'}><Field label={'Endpoint'}><input value={draft.r2Endpoint} onChange={e=>set('r2Endpoint',e.target.value)}/></Field><Field label={'Bucket'}><input value={draft.r2Bucket} onChange={e=>set('r2Bucket',e.target.value)}/></Field><Field label={'Access key ID'}><input value={draft.r2AccessKeyId} onChange={e=>set('r2AccessKeyId',e.target.value)}/></Field>{secret('r2SecretAccessKey','Secret access key',Boolean(view?.r2SecretAccessKeySet))}<Field label={'URL pública base'}><input value={draft.r2PublicBaseUrl} onChange={e=>set('r2PublicBaseUrl',e.target.value)}/></Field></div>)}
 {provider('WordPress','wordpress',<div className={'form-grid'}><Field label={'URL base'}><input type={'url'} required value={draft.wpBaseUrl} onChange={e=>set('wpBaseUrl',e.target.value)}/></Field>{secret('wpHmacSecret','Secreto HMAC',Boolean(view?.wpHmacSecretSet))}<Checkbox label={'Republicar automáticamente'} checked={draft.autoRepublish} onChange={v=>set('autoRepublish',v)}/></div>)}
 <div><button className={'btn-dark'} disabled={saving}>{saving?'Guardando…':'Guardar'}</button></div></form>}</div>;
}

type Product={id:string;name:string;active:boolean};
type Asset={id:string;productId:string;sourceUrl:string|null;url:string|null;storageKey:string|null;isPrimary:boolean;approved:boolean;status:string;origin:string};
type SearchImage={url:string;title?:string;source?:string};
type Mode='remove-bg'|'as-is';
function ImagesTab(){
 const[products,setProducts]=useState<Product[]>([]),[filter,setFilter]=useState(''),[product,setProduct]=useState<Product|null>(null),[assets,setAssets]=useState<Asset[]>([]);
 const[file,setFile]=useState<File|null>(null),[query,setQuery]=useState(''),[images,setImages]=useState<SearchImage[]>([]),[selected,setSelected]=useState<SearchImage|null>(null);
 const[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 useEffect(()=>{api<Product[]>('/products').then(setProducts).catch(e=>setError(errorMessage(e)));},[]);
 const refresh=async(p=product)=>{if(!p)return;setAssets(await api<Asset[]>(`/external-module/products/${p.id}/assets`));};
 const choose=async(p:Product)=>{setProduct(p);setError(null);try{await refresh(p);}catch(e){setError(errorMessage(e));}};
 const run=async(action:()=>Promise<unknown>,message='Acción completada.')=>{setBusy(true);setError(null);setNotice(null);try{await action();await refresh();setNotice(message);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const upload=async(mode:Mode)=>{if(!file||!product)return;await run(async()=>{const form=new FormData();form.append('file',file);await apiUpload(`/external-module/products/${product.id}/assets/upload?mode=${mode}`,form);setFile(null);},mode==='remove-bg'?'Imagen enviada a quitar fondo.':'Imagen guardada tal cual.');};
 const fromSearch=async(mode:Mode)=>{if(!selected||!product)return;await run(async()=>{await api(`/external-module/products/${product.id}/assets/from-url`,{method:'POST',body:{url:selected.url,origin:'SERPER',mode}});setSelected(null);},mode==='remove-bg'?'Imagen enviada a quitar fondo.':'Imagen guardada tal cual.');};
 const filtered=products.filter(p=>p.name.toLowerCase().includes(filter.toLowerCase()));
 return <div style={{display:'grid',gap:16,marginTop:20}}>{error?<Alert tone={'error'}>{error}</Alert>:null}{notice?<Alert tone={'ok'}>{notice}</Alert>:null}
  <section className={'card card-pad'}><h3 className={'panel-title'}>Producto</h3><Field label={'Buscar producto'}><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder={'Nombre del producto'}/></Field><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{filtered.slice(0,30).map(p=><button type={'button'} className={product?.id===p.id?'btn-dark btn-sm':'btn-ghost btn-sm'} key={p.id} onClick={()=>void choose(p)}>{p.name}</button>)}</div></section>
  {!product?null:<><section className={'card card-pad'}><h3 className={'panel-title'}>Subir imagen para {product.name}</h3><input type={'file'} accept={'image/*'} onChange={e=>setFile(e.target.files?.[0]??null)}/>{file?<div style={{marginTop:12}}><img src={URL.createObjectURL(file)} alt={'Preview'} style={{width:180,height:180,objectFit:'contain'}}/><p>Confirmá cómo querés aplicar esta imagen.</p><button disabled={busy} type={'button'} className={'btn-dark btn-sm'} onClick={()=>void upload('remove-bg')}>Quitar fondo</button> <button disabled={busy} type={'button'} className={'btn-ghost btn-sm'} onClick={()=>void upload('as-is')}>Usar tal cual, ya viene sin fondo</button></div>:null}</section>
  <section className={'card card-pad'}><h3 className={'panel-title'}>Buscar en Serper</h3><div style={{display:'flex',gap:8}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Buscar imágenes'}/><button disabled={busy||!query.trim()} type={'button'} className={'btn-dark btn-sm'} onClick={()=>void run(async()=>setImages((await api<{images:SearchImage[]}>('/external-module/serper/images',{query:{q:query}})).images),'Búsqueda completada.')}>Buscar</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(130px,1fr))',gap:12,marginTop:12}}>{images.map((img,i)=><button type={'button'} className={'btn-ghost'} key={`${img.url}-${i}`} onClick={()=>setSelected(img)}><img src={img.url} alt={img.title??'Resultado'} style={{width:'100%',height:110,objectFit:'contain'}}/></button>)}</div>{selected?<div style={{marginTop:16}}><img src={selected.url} alt={'Preview seleccionada'} style={{width:220,height:220,objectFit:'contain'}}/><p>Confirmá cómo querés aplicar la imagen seleccionada.</p><button disabled={busy} type={'button'} className={'btn-dark btn-sm'} onClick={()=>void fromSearch('remove-bg')}>Quitar fondo</button> <button disabled={busy} type={'button'} className={'btn-ghost btn-sm'} onClick={()=>void fromSearch('as-is')}>Usar tal cual</button></div>:null}</section>
  <section className={'card card-pad'}><h3 className={'panel-title'}>Imágenes asociadas</h3>{busy?<Loading label={'Procesando…'}/>:null}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(220px,1fr))',gap:16}}>{assets.map(a=><article key={a.id} className={'card card-pad'}><img src={a.url??a.sourceUrl??''} alt={'Imagen de producto'} style={{width:'100%',height:180,objectFit:'contain'}}/><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{a.isPrimary?<Pill tone={'violet'}>Principal</Pill>:null}<Pill tone={a.status==='READY'?'ok':a.status==='FAILED'?'bad':'warn'}>{a.status}</Pill></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{!a.isPrimary?<button className={'btn-ghost btn-sm'} onClick={()=>void run(()=>api(`/external-module/assets/${a.id}`,{method:'PATCH',body:{isPrimary:true}}))}>Marcar principal</button>:null}{!a.approved?<button className={'btn-ghost btn-sm'} onClick={()=>void run(()=>api(`/external-module/assets/${a.id}`,{method:'PATCH',body:{approved:true}}))}>Aprobar</button>:null}<button className={'btn-ghost btn-sm'} onClick={()=>void run(()=>api(`/external-module/assets/${a.id}/remove-bg`,{method:'POST'}))}>Quitar fondo</button><button className={'btn-ghost btn-sm'} onClick={()=>void run(()=>api(`/external-module/assets/${a.id}/confirm-as-is`,{method:'POST'}))}>Usar tal cual</button><button className={'btn-ghost btn-sm'} onClick={()=>{if(confirm('¿Borrar esta imagen?'))void run(()=>api(`/external-module/assets/${a.id}`,{method:'DELETE'}),'Imagen borrada.');}}>Borrar</button></div></article>)}</div></section></>}
 </div>;
}

type CaseModel={id:string;productId:string;source:'UPLOAD'|'TRIPO'|'SKETCHFAB';sourcePhotos:string[];glbUrl:string|null;status:'PENDING'|'PROCESSING'|'READY'|'FAILED'};
function CaseModelTab(){
 const[products,setProducts]=useState<Product[]>([]),[filter,setFilter]=useState(''),[product,setProduct]=useState<Product|null>(null),[model,setModel]=useState<CaseModel|null>(null);
 const[glb,setGlb]=useState<File|null>(null),[photos,setPhotos]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 useEffect(()=>{void import('@google/model-viewer');api<Product[]>('/products').then(setProducts).catch(e=>setError(errorMessage(e)));},[]);
 const refresh=async(p=product)=>{if(p)setModel(await api<CaseModel|null>(`/external-module/products/${p.id}/case-model`));};
 useEffect(()=>{if(!product||!model||!['PENDING','PROCESSING'].includes(model.status))return;const timer=setInterval(()=>void refresh(product).catch(e=>setError(errorMessage(e))),5000);return()=>clearInterval(timer);},[product,model?.status]);
 const choose=async(p:Product)=>{setProduct(p);setError(null);setNotice(null);try{await refresh(p);}catch(e){setError(errorMessage(e));}};
 const run=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError(null);setNotice(null);try{await action();await refresh();setNotice(message);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const upload=()=>{if(!product||!glb)return;void run(async()=>{const form=new FormData();form.append('file',glb);await apiUpload(`/external-module/products/${product.id}/case-model/upload`,form);setGlb(null);},'Modelo 3D subido.');};
 const generate=()=>{if(!product||photos.length<1||photos.length>4)return;void run(async()=>{const form=new FormData();for(const photo of photos)form.append('photos',photo);await apiUpload(`/external-module/products/${product.id}/case-model/tripo`,form);setPhotos([]);},'Generación con Tripo enviada. El estado se actualizará automáticamente.');};
 const filtered=products.filter(p=>p.name.toLowerCase().includes(filter.toLowerCase()));
 return <div style={{display:'grid',gap:16,marginTop:20}}>{error?<Alert tone={'error'}>{error}</Alert>:null}{notice?<Alert tone={'ok'}>{notice}</Alert>:null}
  <section className={'card card-pad'}><h3 className={'panel-title'}>Producto gabinete</h3><Field label={'Buscar producto'}><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder={'Nombre del gabinete'}/></Field><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{filtered.slice(0,30).map(p=><button type={'button'} className={product?.id===p.id?'btn-dark btn-sm':'btn-ghost btn-sm'} key={p.id} onClick={()=>void choose(p)}>{p.name}</button>)}</div></section>
  {!product?null:<><section className={'card card-pad'}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><h3 className={'panel-title'}>Modelo de {product.name}</h3><button type={'button'} className={'btn-ghost btn-sm'} disabled={busy} onClick={()=>void refresh()}>Actualizar</button></div>{model?<div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}><Pill tone={model.status==='READY'?'ok':model.status==='FAILED'?'bad':'warn'}>{model.status}</Pill><Pill tone={'violet'}>{model.source}</Pill></div>:<Alert tone={'info'}>Este producto todavía no tiene un modelo 3D.</Alert>}{model?.status==='READY'&&model.glbUrl?<model-viewer src={model.glbUrl} camera-controls auto-rotate style={{width:'100%',height:480,background:'#f4f4f5'}}/>:null}{model&&['PENDING','PROCESSING'].includes(model.status)?<Loading label={'Generando modelo 3D…'}/>:null}{model?<div style={{marginTop:12}}><button type={'button'} className={'btn-ghost btn-sm'} disabled={busy} onClick={()=>{if(confirm('¿Borrar este modelo 3D?'))void run(()=>api(`/external-module/case-model/${model.id}`,{method:'DELETE'}),'Modelo 3D borrado.');}}>Borrar</button></div>:null}</section>
  <section className={'card card-pad'}><h3 className={'panel-title'}>Subir modelo propio</h3><input type={'file'} accept={'.glb,.gltf,model/gltf-binary,model/gltf+json'} onChange={e=>setGlb(e.target.files?.[0]??null)}/><div style={{marginTop:12}}><button type={'button'} className={'btn-dark btn-sm'} disabled={busy||!glb} onClick={upload}>Subir GLB</button></div></section>
  <section className={'card card-pad'}><h3 className={'panel-title'}>Generar con Tripo</h3><p>Elegí entre 1 y 4 fotos del gabinete desde distintos ángulos.</p><input type={'file'} accept={'image/*'} multiple onChange={e=>setPhotos(Array.from(e.target.files??[]).slice(0,4))}/><p>{photos.length} foto{photos.length===1?'':'s'} seleccionada{photos.length===1?'':'s'}.</p><button type={'button'} className={'btn-dark btn-sm'} disabled={busy||photos.length<1||photos.length>4} onClick={generate}>Generar con Tripo</button></section></>}
 </div>;
}
