import {createHmac} from'node:crypto';
import {decryptSecret} from'@tgs/config';
import {db} from'@tgs/database';
import {normalizeMediaUrl} from'@tgs/storage';

type LandingLayout={version:1;tokens:{accent:string;bg:string;text:string;radius:number;font?:string};blocks:Array<{type:string;visible:boolean}>};
export type PublishPayload={externalId:string;title:string;slug:string;priceListCents:string;priceCashCents:string;priceTransferCents:string;installments:Array<Record<string,unknown>>;items:Array<{name:string;imageUrl:string|null;description:string|null;specs:Record<string,unknown>}>;model3dUrl:string|null;thumbnailUrl:string|null;heroImageUrl:string|null;descriptionHtml:string|null;power:{watts:number|null;psu:number|null;note:string|null};games:unknown[];compatibility:unknown[];layout:LandingLayout};
export class WordpressPublishError extends Error{constructor(message:string,readonly httpStatus:400|404|502){super(message);this.name='WordpressPublishError';}}
const DEFAULT_LAYOUT:LandingLayout={version:1,tokens:{accent:'#E31B23',bg:'#080B12',text:'#F8FAFC',radius:24,font:'Inter, system-ui, sans-serif'},blocks:['addToCartSticky','specs','description','games','compatibility','payment','recommended'].map(type=>({type,visible:true}))};
const installmentTotal=(base:bigint,bps:number)=>(base*BigInt(10000+bps)+5000n)/10000n;
const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,180);
const jsonSafe=(value:unknown)=>JSON.parse(JSON.stringify(value,(_key,current)=>typeof current==='bigint'?current.toString():current));
function savedLayout(value:unknown):LandingLayout{if(!value||typeof value!=='object')return DEFAULT_LAYOUT;const layout=value as Partial<LandingLayout>;return layout.version===1&&layout.tokens&&Array.isArray(layout.blocks)?layout as LandingLayout:DEFAULT_LAYOUT;}
export async function buildPublishPayload(quoteVersionId:string):Promise<PublishPayload>{
 const version=await db.quoteVersion.findUnique({where:{id:quoteVersionId},include:{family:{include:{heroAsset:true}},enrichment:true,webPublication:true,items:{orderBy:{position:'asc'},include:{line:true,product:{include:{assets:{where:{status:'READY',url:{not:null}},orderBy:[{isPrimary:'desc'},{createdAt:'desc'}]},caseModel3D:true}}}}}});if(!version)throw new WordpressPublishError('Versión de presupuesto inexistente',404);
 const company=await db.companySettings.findUniqueOrThrow({where:{id:'singleton'}});const activePlans=await db.financingPlan.findMany({where:{active:true},orderBy:{sortOrder:'asc'}});const snapshot=version.financingSnapshot;const plans=Array.isArray(snapshot)?snapshot:(snapshot&&typeof snapshot==='object'&&Array.isArray((snapshot as any).plans)?(snapshot as any).plans:activePlans);const list=installmentTotal(version.totalSaleCents,company.listInterestBps);const enriched=version.enrichment;const items=version.items.map(item=>{const imageUrl=normalizeMediaUrl(item.product?.assets[0]?.url)??null;return{name:item.frozenName,imageUrl,description:item.observation??item.product?.description??null,specs:{quantity:item.quantity,line:item.line?.name??null,unitPriceCents:item.frozenSalePriceCents.toString(),subtotalCents:item.subtotalCents.toString()}};});const models=version.items.filter(item=>item.product?.caseModel3D?.status==='READY'&&item.product.caseModel3D.glbUrl);const preferred=models.find(item=>/gabinete|case/i.test(`${item.line?.name??''} ${item.frozenName}`))??models[0];const config=await db.externalModuleConfig.findUnique({where:{id:'singleton'},select:{landingLayoutJson:true}});
 return{externalId:version.id,title:version.family.internalName||version.family.visibleNumber,slug:slugify(`${version.family.internalName}-${version.family.visibleNumber}`),priceListCents:list.toString(),priceCashCents:version.totalSaleCents.toString(),priceTransferCents:version.totalSaleCents.toString(),installments:plans.map((plan:any)=>{const total=installmentTotal(list,Number(plan.interestBps??0));return{bank:plan.bank??null,installments:Number(plan.installments),interestBps:Number(plan.interestBps??0),totalCents:total.toString(),installmentCents:((total+BigInt(Number(plan.installments))/2n)/BigInt(Number(plan.installments))).toString()};}),items,model3dUrl:normalizeMediaUrl(preferred?.product?.caseModel3D?.glbUrl)??null,thumbnailUrl:normalizeMediaUrl(version.family.thumbnailUrl??version.webPublication?.thumbnailUrl)??null,heroImageUrl:normalizeMediaUrl(version.family.heroAsset?.url??version.family.thumbnailUrl??version.webPublication?.thumbnailUrl)??null,descriptionHtml:enriched?.descriptionHtml??null,power:{watts:enriched?.powerWatts??null,psu:enriched?.recommendedPsuWatts??null,note:enriched?.powerNote??null},games:Array.isArray(enriched?.gamesJson)?enriched.gamesJson:[],compatibility:Array.isArray(enriched?.compatibilityJson)?enriched.compatibilityJson:[],layout:savedLayout(config?.landingLayoutJson)};
}
export async function publishQuote(quoteVersionId:string){const payload=await buildPublishPayload(quoteVersionId);try{const config=await db.externalModuleConfig.findUniqueOrThrow({where:{id:'singleton'}});if(!config.wpHmacSecretEnc)throw new WordpressPublishError('Configurá el secreto HMAC de WordPress',400);const body=JSON.stringify(jsonSafe(payload));const signature=createHmac('sha256',decryptSecret(config.wpHmacSecretEnc)).update(body).digest('hex');let response:Response;try{response=await fetch(`${config.wpBaseUrl.replace(/\/$/,'')}/wp-json/tgs/v1/publish`,{method:'POST',headers:{'content-type':'application/json','X-TGS-Signature':signature},body});}catch{throw new WordpressPublishError('No se pudo conectar con WordPress',502);}const text=await response.text();let wpResponse:any={};try{wpResponse=text?JSON.parse(text):{};}catch{}if(!response.ok)throw new WordpressPublishError(wpResponse?.message??`WordPress respondió HTTP ${response.status}`,502);if(!wpResponse?.ok||!wpResponse?.productId)throw new WordpressPublishError('WordPress devolvió una respuesta inválida',502);const webPublication=await db.webPublication.upsert({where:{quoteVersionId},create:{quoteVersionId,status:'PUBLISHED',wpProductId:String(wpResponse.productId),url:wpResponse.url??null,thumbnailUrl:payload.thumbnailUrl,payloadSnapshot:payload as any,publishedAt:new Date()},update:{status:'PUBLISHED',wpProductId:String(wpResponse.productId),url:wpResponse.url??null,thumbnailUrl:payload.thumbnailUrl,payloadSnapshot:payload as any,lastError:null,publishedAt:new Date()}});return{webPublication,wpResponse};}catch(error){await db.webPublication.upsert({where:{quoteVersionId},create:{quoteVersionId,status:'FAILED',payloadSnapshot:payload as any,lastError:error instanceof Error?error.message:'Error al publicar'},update:{status:'FAILED',payloadSnapshot:payload as any,lastError:error instanceof Error?error.message:'Error al publicar'}});throw error;}}
