export type QuoteState = "BORRADOR" | "ENVIADO" | "ACEPTADO" | "RECHAZADO" | "REEMPLAZADO" | "NO_CONCRETADO";
export type RequestState = "PENDIENTE" | "EN_PREPARACION" | "LISTA" | "ENVIADA" | "CERRADA";
export type PdfKind = "SIMPLE" | "DETALLADO";
export type FieldOverride = "HEREDAR" | "MOSTRAR" | "OCULTAR";
export type ReplyIntent = "ACEPTA" | "RECHAZA" | "PIDE_CAMBIO" | "CONSULTA" | "AMBIGUA";
export type SendAttemptStatus = "PENDIENTE" | "CONFIRMADO_AUTO" | "CONFIRMADO_MANUAL" | "NO_ENVIADO" | "AMBIGUO";
export type Customer = {id:string;name:string;normalizedName?:string;phone:string|null;normalizedPhone?:string|null;dni:string|null;notes?:string|null};
export type PcLine = {id:string;name:string;sortOrder:number;active:boolean;keyLine:boolean;concept:string};
export type Product = {id:string;name:string;costCents:string;salePriceCents:string;markupBps:number;defaultLineId:string|null;defaultLine?:PcLine|null;active:boolean;imageUrl?:string|null;brand?:string|null;mpn?:string|null};
export type AcustockProduct={id:string;name:string;mpn:string;title:string;description:string;priceCents:string;salePriceCents:string;stockQuantity:number;availability:string;brand:string|null;productType:string|null;imageUrl:string|null;productUrl:string};
export type AcustockProductSearch={items:AcustockProduct[];total:number;page:number;pageSize:number;lastSyncedAt:string|null};
export type QuoteItem = {id?:string;productId?:string|null;frozenName?:string;name?:string;lineId?:string|null;line?:PcLine|null;quantity:number;frozenCostCents?:string;costCents?:string;frozenMarkupBps?:number;markupBps?:number;frozenSalePriceCents?:string;salePriceCents?:string;subtotalCents?:string;position?:number;observation?:string|null;isPcMainLine?:boolean};
export type QuoteVersion = {id:string;version:number;state:QuoteState;reason?:string|null;createdAt?:string;creator?:{id:string;username:string;displayName:string|null};totalSaleCents:string;totalCostCents:string;profitCents:string;publicObservation:string|null;resolvedPdfConfig?:Record<string,unknown>;pdfOverrides?:Record<string,FieldOverride>;sentMessage:string|null;sentAt:string|null;items:QuoteItem[];pdfs?:QuotePdf[]};
export type Quote = {id:string;visibleNumber:string;internalName:string;requestId:string|null;customerId:string|null;isBuiltPc:boolean;activeVersion:number;customer?:Customer|null;version:QuoteVersion|null;versions:QuoteVersion[];items:QuoteItem[]};
export type QuoteSearchResult={total:number;page:number;pageSize:number;items:Quote[]};
export type Collection={id:string;name:string;description:string|null;archived:boolean;favorite:boolean;visibleInExtension:boolean;quotes?:{familyId:string;family:Quote}[]};
export type QuoteRequest={id:string;title:string;originalText:string;customerId:string|null;detectedPhone:string|null;state:RequestState;customer?:Customer|null;families?:{id:string;visibleNumber:string}[]};
export type SendAttempt={id:string;versionId:string;chatPhone:string|null;chatName:string|null;message:string;pdfKind:PdfKind|null;pdfName?:string|null;status:SendAttemptStatus;confidence:number|null;createdAt:string};
export type QuoteStatusEvent={id:string;type:string;createdAt:string;metadata?:unknown;versionNumber?:number|null;description?:string;descriptions?:string[];creator?:{id:string;displayName:string|null;username:string}|null};
export type QuoteTimeline={events:QuoteStatusEvent[];attempts:SendAttempt[]};
export type LatestSentQuote={delivery:{id:string;deliveredAt:string;chatPhone:string|null};quote:Quote};
export type QuotePdf={id:string;kind:PdfKind;reused?:boolean;immutable?:boolean};
export type NotificationRow={id:string;title:string;body:string;type:string;chatPhone:string|null;draft?:string|null;entityId?:string|null;metadata?:Record<string,unknown>|null;createdAt:string;readAt:string|null;actedAt:string|null};
export type AiSuggestion={result:{text:string};metadata:{usedAi:boolean;cacheHit:boolean}};
export type QuoteItemInput={productId:string|null;name:string;lineId:string|null;quantity:number;costCents:string;markupBps:number;salePriceCents:string;position:number;observation:string|null;isPcMainLine:boolean};
export type ChatbotMode="OFF"|"SUGGEST"|"AUTO";
export type ChatbotResponseEntry={id:string;enabled:boolean;activators:string[];similarityThreshold:number;answer:string;context:string;attachments:{imageUrl:string|null;url:string|null;quote:{familyId:string;version:number|null;useLatest:boolean}|null}};
export type ChatbotSettings={id:"singleton";updatedAt?:string;enabled:boolean;defaultMode:ChatbotMode;model:string|null;persona:string;openingMessages:string[];closingMessages:string[];responses:ChatbotResponseEntry[];escalationKeywords:string[];escalationInstructions:string;modelCanEscalate:boolean;businessHours:{enabled:boolean;timezone:string;schedule:Record<"monday"|"tuesday"|"wednesday"|"thursday"|"friday"|"saturday"|"sunday",Array<{from:string;to:string}>>};outsideHoursBehavior:{mode:"OFF"|"STALL"|"NORMAL";message:string};responseStyle:{length:"SHORT"|"MEDIUM"|"DETAILED";maxCharacters:number;emoji:"NONE"|"SPARING"|"NATURAL";paragraphs:"COMPACT"|"SHORT"|"FREE";avoidRepetition:boolean};productMessageIntro:string;quoteSendPrompt:string;ignoredAutoMessages:string[];autoDelayMaxSeconds:number;reuseSimilarityThreshold:number;recontactEnabled:boolean;recontactDays:number;recontactPrompt:string;recontactMaxAttempts:number;scanIntervalSeconds:number;maxRecentSnippets:number;summaryRefreshEvery:number;sendConfirmationTimeoutMs:number;multiMessage:{enabled:boolean;splitMode:"AI_NATURAL"|"AI_PLUS_FIXED"|"FIXED_ONLY";maxBubbles:number;openingMessage:string;closingMessage:string;quoteFollowup:{enabled:boolean;message:string};draftMode:"QUEUE"|"JOINED"|"FIRST_ONLY";betweenDelayMinSeconds:number;betweenDelayMaxSeconds:number}};
export type ChatbotMessageSnippet={direction:"INBOUND"|"OUTBOUND";text:string};
export type ChatbotRecontactCandidate={chatKey:string;displayName:string|null;lastOutboundAt:string;recontactCount:number;daysSince:number};
export type ChatbotRecontactInput={chatKey:string;displayName?:string;recentMessages?:ChatbotMessageSnippet[]};
export type ChatbotRecontactResult={reply?:string;logId?:string;action:"SUGGESTED"|"DISABLED"|"RECONTACT_DISABLED"};
export type ChatbotRecontactMarkResult={action:"MARKED_SENT";recontactCount:number;lastRecontactAt:string};
export type ChatbotResolvedAttachment={
  ruleId:string;
  image?:{url:string;filename:string};
  quote?:{familyId:string;version:number;visibleNumber:string;filename:string};
};
export type ChatbotNativeStatus="ESCALATED"|"UNRESOLVED"|"PENDING_REQUEST"|"SUGGESTION"|"RESPONDED";
export type ChatbotConversation={chatKey:string;displayName?:string|null;modeOverride:ChatbotMode|null;effectiveMode:ChatbotMode;escalatedAt:string|null;escalationReason?:string|null;activeRequestId?:string|null;lastQuoteFamilyId?:string|null;lastQuoteVersion?:number|null;nativeStatus?:{status:ChatbotNativeStatus;label:string}|null};
export type ChatbotLog={id:string;conversationKey:string;direction:"INBOUND"|"OUTBOUND";actor:"CUSTOMER"|"BOT"|"HUMAN"|"SYSTEM";mode:ChatbotMode|null;status:string;text:string;notificationId?:string|null;error?:string|null;decisionMetadata?:Record<string,unknown>|null;createdAt:string};
export type ChatbotRespondResult={action:"DUPLICATE"|"OFF"|"DISABLED"|"ESCALATED"|"OUTSIDE_HOURS"|"SUGGESTED"|"AUTO_REPLY"|"SIMULATED";effectiveMode:ChatbotMode;autoSend:boolean;reply?:string;messages?:string[];quoteFollowupMessage?:string|null;logId?:string;notificationId?:string|null;duplicateStatus?:string;autoDelayMaxSeconds?:number;simulation?:boolean;wouldEscalate?:{reason:string|null};reused?:{sourceInboundLogId:string;sourceOutboundLogId:string;similarity:number};attachments?:ChatbotResolvedAttachment[];request?:{id:string;title:string;state:string;created:boolean};multiMessage?:{draftMode:"QUEUE"|"JOINED"|"FIRST_ONLY";betweenDelayMinSeconds:number;betweenDelayMaxSeconds:number}};
export type ChatbotChatContext={chatKey:string;phone:string|null;customer:Customer|null;requests:QuoteRequest[];activeRequestId:string|null};
