export type QuoteState = "BORRADOR" | "ENVIADO" | "ACEPTADO" | "RECHAZADO" | "REEMPLAZADO" | "NO_CONCRETADO";
export type RequestState = "PENDIENTE" | "EN_PREPARACION" | "LISTA" | "ENVIADA" | "CERRADA";
export type PdfKind = "SIMPLE" | "DETALLADO";
export type FieldOverride = "HEREDAR" | "MOSTRAR" | "OCULTAR";
export type ReplyIntent = "ACEPTA" | "RECHAZA" | "PIDE_CAMBIO" | "CONSULTA" | "AMBIGUA";
export type SendAttemptStatus = "PENDIENTE" | "CONFIRMADO_AUTO" | "CONFIRMADO_MANUAL" | "NO_ENVIADO" | "AMBIGUO";
export type Customer = {id:string;name:string;normalizedName?:string;phone:string|null;normalizedPhone?:string|null;dni:string|null;notes?:string|null};
export type PcLine = {id:string;name:string;sortOrder:number;active:boolean;keyLine:boolean;concept:string};
export type Product = {id:string;name:string;costCents:string;salePriceCents:string;markupBps:number;defaultLineId:string|null;defaultLine?:PcLine|null;active:boolean};
export type QuoteItem = {id?:string;productId?:string|null;frozenName?:string;name?:string;lineId?:string|null;line?:PcLine|null;quantity:number;frozenCostCents?:string;costCents?:string;frozenMarkupBps?:number;markupBps?:number;frozenSalePriceCents?:string;salePriceCents?:string;subtotalCents?:string;position?:number;observation?:string|null;isPcMainLine?:boolean};
export type QuoteVersion = {id:string;version:number;state:QuoteState;reason?:string|null;createdAt?:string;creator?:{id:string;username:string;displayName:string|null};totalSaleCents:string;totalCostCents:string;profitCents:string;publicObservation:string|null;resolvedPdfConfig?:Record<string,unknown>;pdfOverrides?:Record<string,FieldOverride>;sentMessage:string|null;sentAt:string|null;items:QuoteItem[];pdfs?:QuotePdf[]};
export type Quote = {id:string;visibleNumber:string;internalName:string;requestId:string|null;customerId:string|null;isBuiltPc:boolean;activeVersion:number;customer?:Customer|null;version:QuoteVersion|null;versions:QuoteVersion[];items:QuoteItem[]};
export type QuoteSearchResult={total:number;page:number;pageSize:number;items:Quote[]};
export type Collection={id:string;name:string;description:string|null;archived:boolean;favorite:boolean;visibleInExtension:boolean;quotes?:{familyId:string;family:Quote}[]};
export type QuoteRequest={id:string;title:string;originalText:string;customerId:string|null;detectedPhone:string|null;state:RequestState;customer?:Customer|null;families?:{id:string;visibleNumber:string}[]};
export type SendAttempt={id:string;versionId:string;chatPhone:string|null;chatName:string|null;message:string;pdfKind:PdfKind|null;pdfName?:string|null;status:SendAttemptStatus;confidence:number|null;createdAt:string};
export type QuoteStatusEvent={id:string;type:string;createdAt:string;metadata?:unknown;versionNumber?:number|null;description?:string;descriptions?:string[];creator?:{id:string;displayName:string|null;username:string}|null};
export type QuoteTimeline={events:QuoteStatusEvent[];attempts:SendAttempt[]};
export type LatestSentQuote={delivery:{id:string;deliveredAt:string;chatPhone:string|null};quote:Quote};
export type QuotePdf={id:string;kind:PdfKind;reused?:boolean;immutable?:boolean};
export type NotificationRow={id:string;title:string;body:string;type:string;chatPhone:string|null;draft?:string|null;entityId?:string|null;metadata?:Record<string,unknown>|null;createdAt:string;readAt:string|null;actedAt:string|null};
export type AiSuggestion={result:{text:string};metadata:{usedAi:boolean;cacheHit:boolean}};
export type QuoteItemInput={productId:string|null;name:string;lineId:string|null;quantity:number;costCents:string;markupBps:number;salePriceCents:string;position:number;observation:string|null;isPcMainLine:boolean};
export type ChatbotMode="OFF"|"SUGGEST"|"AUTO";
export type ChatbotSettings={id:"singleton";enabled:boolean;defaultMode:ChatbotMode;ignoredAutoMessages:string[];autoDelayMaxSeconds:number;reuseSimilarityThreshold:number;scanIntervalSeconds:number;maxRecentSnippets:number;sendConfirmationTimeoutMs:number};
export type ChatbotResolvedAttachment={
  ruleId:string;
  image?:{url:string;filename:string};
  quote?:{familyId:string;version:number;visibleNumber:string;filename:string};
};
export type ChatbotNativeStatus="ESCALATED"|"UNRESOLVED"|"PENDING_REQUEST"|"SUGGESTION"|"RESPONDED";
export type ChatbotConversation={chatKey:string;displayName?:string|null;modeOverride:ChatbotMode|null;effectiveMode:ChatbotMode;escalatedAt:string|null;escalationReason?:string|null;activeRequestId?:string|null;nativeStatus?:{status:ChatbotNativeStatus;label:string}|null};
export type ChatbotLog={id:string;conversationKey:string;direction:"INBOUND"|"OUTBOUND";actor:"CUSTOMER"|"BOT"|"HUMAN"|"SYSTEM";mode:ChatbotMode|null;status:string;text:string;notificationId?:string|null;error?:string|null;decisionMetadata?:Record<string,unknown>|null;createdAt:string};
export type ChatbotRespondResult={action:"DUPLICATE"|"OFF"|"DISABLED"|"ESCALATED"|"OUTSIDE_HOURS"|"SUGGESTED"|"AUTO_REPLY"|"SIMULATED";effectiveMode:ChatbotMode;autoSend:boolean;reply?:string;logId?:string;notificationId?:string|null;duplicateStatus?:string;autoDelayMaxSeconds?:number;simulation?:boolean;wouldEscalate?:{reason:string|null};reused?:{sourceInboundLogId:string;sourceOutboundLogId:string;similarity:number};attachments?:ChatbotResolvedAttachment[];request?:{id:string;title:string;state:string;created:boolean}};
export type ChatbotChatContext={chatKey:string;phone:string|null;customer:Customer|null;requests:QuoteRequest[];activeRequestId:string|null};
